<html>
    <head>
        <meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
        <meta charset="UTF-8"/>
        <title>RESERVA</title>
        <style type="text/css">
            body {
                padding-top: 0 !important;
                padding-bottom: 0 !important;
                padding-top: 0 !important;
                padding-bottom: 0 !important;
                margin:0 !important;
                width: 100% !important;
                -webkit-text-size-adjust: 100% !important;
                -ms-text-size-adjust: 100% !important;
                -webkit-font-smoothing: antialiased !important;
            }
            .tableContent img {
                border: 0 !important;
                display: block !important;
                outline: none !important;
            }
            ul{
                margin:0;
            }
            p{
                color:white; /* #999999;*/
                font-size:13px;
                line-height:19px;
                margin:0;
            }
            h2,h1 {
                color:#555555;
                font-size:21px;
                font-weight:normal;
                margin: 0;
            }
            h2.white{
                color:#ffffff;
            }
            a{
                color:#000000;
            }
            a.link1{
                font-size:13px;
                color:#52999E;
                font-weight:bold;
                text-decoration:none;
            }
            a.link2{
                padding:8px;
                background:#52999E;
                font-size:13px;
                color:#ffffff;
                text-decoration:none;
                font-weight:bold;
            }
            .bgBody{
                background: #F6F6F6;
            }
            .bgItem{
                background: #ffffff;
            }

            @media only screen and (max-width:480px)

            {

            table[class="MainContainer"], td[class="cell"] 
                    {
                            width: 100% !important;
                            height:auto !important; 
                    }
            td[class="specbundle"] 
                    {
                            width: 100% !important;
                            float:left !important;
                            font-size:14px !important;
                            line-height:18px !important;
                            display:block !important;
                            padding-bottom:15px !important;
                    }

            td[class="spechide"] 
                    {
                            display:none !important;
                    }
                        img[class="banner"] 
                    {
                              width: 100% !important;
                              height: auto !important;
                    }

            }
	
            @media only screen and (max-width:540px) 

            {

            table[class="MainContainer"], td[class="cell"] 
                    {
                            width: 100% !important;
                            height:auto !important; 
                    }
            td[class="specbundle"] 
                    {
                            width: 100% !important;
                            float:left !important;
                            font-size:14px !important;
                            line-height:18px !important;
                            display:block !important;
                            padding-bottom:15px !important;
                    }

            td[class="spechide"] 
                    {
                            display:none !important;
                    }
                        img[class="banner"] 
                    {
                              width: 100% !important;
                              height: auto !important;
                    }

            }
        </style>

        <script type="colorScheme" class="swatch active">
          {
            "name":"Default",
            "bgBody":"F6F6F6",
            "link":"52999E",
            "color":"999999",
            "bgItem":"ffffff",
            "title":"555555"
          }
        </script>
    </head>
    <body class='bgBody' leftpadding="0" offset="0" paddingheight="0" paddingwidth="0" style="padding-top: 0; padding-bottom: 0; padding-top: 0; padding-bottom: 0; background-repeat: repeat; width: 100% !important; -webkit-text-size-adjust: 100%; -ms-text-size-adjust: 100%; -webkit-font-smoothing: antialiased;" toppadding="0">
        <table align="center" bgcolor="#f6f6f6" border="0" cellpadding="0" cellspacing="0" class="tableContent" width="100%">
            <tbody>
            <tr>
              <td><table align="center" bgcolor="#f6f6f6" border="0" cellspacing="0" style="font-family:helvetica, sans-serif;" width="600" class="MainContainer">
            <tbody>
            <tr>
              <td>
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tbody>
            <tr>
              <td valign="top" width="20">&nbsp;</td>
              <td valign="top">
                  <table width="100%" border="0" cellspacing="0" cellpadding="0">

                <!--  =========================== The header ===========================  -->
                <tbody>
                <tr>
                <!--  =========================== The body ===========================  -->
                  <td class="movableContentContainer">
                  
                    <div class="movableContent" style="border: 0px; padding-top: 0px; position: relative;">
                            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                <tr>
                                        <td height="25">
                                        </td>
                                </tr>
                                <tr>
                                    <td>
                                    <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
                                        <tbody>
                                            <tr>
                                                <td align="left" valign="middle">
                                                    <div class="contentEditableContainer contentImageEditable">
                                                        <div class="contentEditable">
                                                            <img alt="Company logo" data-default="placeholder" data-max-width="300" height="27" src="<?= 'http://localhost/sellers/public' . '/images/logo-business.jpg'; ?>" width="107" />
                                                        </div>
                                                    </div>
                                                </td>
                                    <td align="right" valign="top">
                                        <div class="contentEditableContainer contentImageEditable" style="display:inline-block;">
                                            <div class="contentEditable">
<!--                                                <a target='_blank' href="[SHOWEMAIL]" style="color:#A8B0B6;font-size:13px;text-decoration:none;">Open in your browser</a>-->
                                            </div>
                                        </div>
                                    </td>
                                    <td align="right" valign="top" width="18">
                                        <div class="contentEditableContainer contentImageEditable" style="display:inline-block;">
                                            <div class="contentEditable">
<!--                                                <a target='_blank' href="[SHOWEMAIL]">
                                                    <img alt="open in browser image" data-default="placeholder" height="15" src="images/openBrowser.png" style="padding-left:10px;" width="15" />
                                                </a>-->
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                                    </td>
                            </tr>
                    </table>
        </div>
       
        <div class="movableContent" style="border: 0px; padding-top: 0px; position: relative;">
            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tbody>
                    <tr>
                        <td height="25">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table align="center" border="0" cellpadding="0" cellspacing="0" valign="top" width="100%">
                                <tbody>
                                    <tr>
                                        <td bgcolor="#f6f6f6" style="border:1px solid #dddddd;" width="269" class="specbundle">
                                            <table align="center" bgcolor="#52999E" border="0" cellpadding="0" cellspacing="0" valign="top" width="100%">
                                                <tbody>
                                                    <tr>
                                                        <td colspan="3" height="9">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td width="9">
                                                        </td>
                                                        <td width="251" align="left" valign="middle">
                                                            <div class="contentEditableContainer contentImageEditable">
                                                                <div class="contentEditable">
                                                                    <h2 class='white' style="color:#ffffff;font-size:21px;font-weight:normal;">
                                                                        ANUNCIO</h2>                                                                    
                                                                    <ul style="padding-left: 2px; list-style:none;">
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p><?= utf8_decode($this->anuncio['0']['address_ad']); ?></p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>CP: <?= $this->anuncio['0']['zip']; ?></p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Poblaci&oacute;n: <?= $this->anuncio['0']['city']; ?></p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Provincia: <?= $this->anuncio['0']['provincia']; ?></p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Pais: Espa&ntilde;a</p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p style="margin-top: 10px;">
                                                                                <a target="_blank" href="<?= 'http://localhost/sellers/public' . '/habitacion/?id=' . $this->anuncio['0']['id']; ?>" style="color:#FFFFFF;font-size:15px; font-weight: bold; text-decoration:none;">DETALLES ALOJAMIENTO</a>
                                                                            </p>
                                                                        </li>
                                                                    </ul>
                                                                </div>
                                                            </div>
                                                        </td>
                                                        <td width="9">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="3" height="9">
                                                        </td>
                                                    </tr>
                                                 </tbody>
                                            </table>
                                        </td>
                                        <td width="18" class="specbundle">&nbsp;</td>
                                        <td bgcolor="#f6f6f6" style="border:1px solid #dddddd;" width="269"  class="specbundle">
                                            <table align="center" bgcolor="#52999E" border="0" cellpadding="0" cellspacing="0" valign="top" width="100%">
                                                <tbody>
                                                    <tr>
                                                        <td colspan="3" height="9">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td width="9">
                                                        </td>
                                                        <td width="251" align="left" valign="middle">
                                                            <div class="contentEditableContainer contentTextEditable">
                                                                <div class="contentEditable">
                                                                    <h2 class='white' style="color:#ffffff;font-size:21px;font-weight:normal;">
                                                                        <?= $this->anuncio['0']['title_ad']; ?></h2>                                                                    
                                                                    <ul style="padding-left: 2px; list-style:none;">
                                                                        <?php
                                                                            $url = 'http://localhost/sellers/public' . '/habitacion/?id=' . $this->anuncio['0']['id'];
                                                                        ?>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>
                                                                                <?= Application_Model_System_Util::myTruncate(utf8_decode($this->anuncio['0']['comments_ad']), 200, " ", " <a target='_blank' title='M&aacute;s informaci&oacute;n' href='" . $url . "' style='color:#FFFFFF;font-size:15px; font-weight: bold;color:#FFFFFF;font-size:15px; font-weight: bold;text-decoration:none;'> ... </a> ");  ?>
                                                                            </p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p style="margin-top: 10px;">
                                                                                <a target="_blank" href="<?= $url; ?>" style="color:#FFFFFF;font-size:15px; font-weight: bold; text-decoration:none;">M&Aacute;S INFORMACI&Oacute;N</a>
                                                                            </p>
                                                                        </li>
                                                                    </ul>    
                                                                </div>
                                                            </div>
                                                        </td>
                                                        <td width="9">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="3" height="9">
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

                    
                    
                    
                    
        <div class="movableContent" style="border: 0px; padding-top: 0px; position: relative;">
            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                    <td align="center" bgcolor="#275D61" style="padding:20px;">
                        <div class="contentEditableContainer contentTextEditable">
                            <div class="contentEditable">
                                <p style="color:#ffffff;font-size:16px;line-height:19px;">
                                    Presupuesto proforma de la reserva de este alojamiento.
                                </p>
                            </div>
                        </div>
                    </td>
                </tr>
            </table>
        </div>
          
        <div class="movableContent" style="border: 4px; padding-top: 0px; position: relative;">
            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tbody>
                    <tr>
                        <td height="25">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table align="center" border="0" cellpadding="0" cellspacing="0" valign="top" width="100%">
                                <tbody>
                                    <tr>
                                        <td bgcolor="#f6f6f6" style="border:1px solid #dddddd;" width="269" class="specbundle">
                                            <table align="center" bgcolor="#52999E" border="0" cellpadding="0" cellspacing="0" valign="top" width="100%">
                                                <tbody>
                                                    <tr>
                                                        <td colspan="3" height="9">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td width="9">
                                                        </td>
                                                        <td width="251" align="left" valign="middle">
                                                            <div class="contentEditableContainer contentTextEditable">
                                                            
                                                                <div class="contentEditable">
                                                                    <h2 class='white' style="color:#ffffff;font-size:21px;font-weight:normal;">
                                                                        C&Oacute;DIGO DE OPERACI&Oacute;N </h2>
                                                                    <ul class='white' style="padding-left: 2px; list-style:none; color:#ffffff;">
                                                                        <li style="font-size:13px;line-height:19px; color:#ffffff;">
                                                                            <p><span style="font-weight:bold;">95664589-AV</span></p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>&nbsp;</p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>&nbsp;</p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>&nbsp;</p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>&nbsp;</p>
                                                                        </li>
                                                                    </ul>
                                                                </div>                                                                      
                                                            
                                                            </div>
                                                        </td>
                                                        <td width="9">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="3" height="9">
                                                        </td>
                                                    </tr>
                                                 </tbody>
                                            </table>
                                        </td>
                                        <td width="18" class="specbundle">&nbsp;</td>
                                        <td bgcolor="#f6f6f6" style="border:1px solid #dddddd;" width="269"  class="specbundle">
                                            <table align="center" border="0" cellpadding="0" cellspacing="0" valign="top" width="100%">
                                                <tbody>
                                                    <tr>
                                                        <td colspan="3" height="9">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td width="9">
                                                        </td>
                                                        <td width="251" align="center" valign="middle">
                                                            <div class="contentEditableContainer contentImageEditable">
                                                                <div class="contentEditable"><!-- $this->baseUrl()  http://localhost/sellers/public -->
                                                                    <img alt="product image" data-default="placeholder" data-max-width="251" height="142" src="<?php echo 'http://localhost/sellers/public' . '/ads/images/57/' . $this->anuncio["0"]["id"] . '/home/' . $this->pic['0']['file_name']; ?>" width="251" />
                                                                </div>
                                                            </div>
                                                        </td>
                                                        <td width="9">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="3" height="9">
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    <?php 
        $nights = (int)$this->book['0']['interval'];
        $price = (double)$this->anuncio['0']['price_ad'];
        $porcentajeGasto = (int)number_format($this->anuncio['0']['gasto_tramite'],0);
        $gastosTramite = $nights*$price*$porcentajeGasto/100;
        $limpieza = (int)number_format($this->anuncio['0']['limpieza'],0);
        $subTotal = $nights*$price+$gastosTramite+$limpieza;
        $fianza = (double)number_format($this->anuncio['0']['fianza'],0);
    ?>
                      

        <div class="movableContent" style="border: 0px; padding-top: 0px; position: relative;">
            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                <tbody>
                    <tr>
                        <td height="25">
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <table align="center" border="0" cellpadding="0" cellspacing="0" valign="top" width="100%">
                                <tbody>
                                    <tr>
                                        <td bgcolor="#f6f6f6" style="border:1px solid #dddddd;" width="269" class="specbundle">
                                            <table align="center" bgcolor="#52999E" border="0" cellpadding="0" cellspacing="0" valign="top" width="100%">
                                                <tbody>
                                                    <tr>
                                                        <td colspan="3" height="9">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td width="9">
                                                        </td>
                                                        <td width="251" align="left" valign="middle">
                                                            <div class="contentEditableContainer contentImageEditable">
                                                                
                                                                <div class="contentEditable">
                                                                    <h2 class='white' style="color:#ffffff;font-size:21px;font-weight:normal;">
                                                                        DATOS DE FACTURACI&Oacute;N</h2>
                                                                    <ul class='white' style="padding-left: 2px; list-style:none; color:#ffffff;">
                                                                        <li style="font-size:13px;line-height:19px; color:#ffffff;">
                                                                            <p>Nombre: <?= utf8_decode($this->bill['0']['billing_name']); ?></p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>NIE/NIF/DNI: <?= utf8_decode($this->bill['0']['billing_document']); ?></p>
                                                                        </li>
<!--                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>E-mail: <?php // utf8_decode($this->book['0']['booking_email']); ?></p>
                                                                        </li>-->
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Tel&eacute;fono: <?= utf8_decode($this->bill['0']['billing_phone']); ?></p>
                                                                        </li>
                                                                    </ul>
                                                                </div>                                                                
                                                                
                                                                
                                                                <div class="contentEditable">
                                                                    <h2 class='white' style="color:#ffffff;font-size:21px;font-weight:normal;">
                                                                        DIRECCI&Oacute;N</h2>                                                                    
                                                                    <ul style="padding-left: 2px; list-style:none;">
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p><?= utf8_decode($this->bill['0']['billing_address']); ?></p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>CP: <?= utf8_decode($this->bill['0']['billing_zip']); ?></p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Poblaci&oacute;n: <?= utf8_decode($this->bill['0']['billing_city']); ?></p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Provincia: <?= utf8_decode($this->bill['0']['billing_provincia']); ?></p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Pais: Espa&ntilde;a</p>
                                                                        </li>
                                                                    </ul>
                                                                </div>
                                                                
                                                                <div class="contentEditable" style="margin-top: 20px; background-color: #275D61;">
                                                                    <h2 class='white' style="color:#ffffff;font-size:21px;font-weight:normal;">
                                                                        CONFIRMACI&Oacute;N DE LA RESERVA</h2>                                                                  
                                                                    
                                                                    <ul style="padding-left: 2px; list-style:none;">
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Ingrese el correspondiente importe:</p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Titular de la cuenta <span style="font-weight:bold;">Sr. Mario Gonzales Perez</span></p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Cuenta Nro <span style="font-weight:bold;">12345678901234567890</span></p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Importe total <span style="font-weight:bold;"><?= number_format($subTotal+$subTotal*0.21+$fianza,2,",","."); ?> &euro;</span></p>
                                                                        </li>
                                                                        
                                                                    </ul>
                                                                </div>
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                            </div>
                                                        </td>
                                                        <td width="9">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="3" height="9">
                                                        </td>
                                                    </tr>
                                                 </tbody>
                                            </table>
                                        </td>
                                        <td width="18" class="specbundle">&nbsp;</td>
                                        <td bgcolor="#f6f6f6" style="border:1px solid #dddddd;" width="269"  class="specbundle">
                                            <table align="center" bgcolor="#52999E" border="0" cellpadding="0" cellspacing="0" valign="top" width="100%">
                                                <tbody>
                                                    <tr>
                                                        <td colspan="3" height="9">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td width="9">
                                                        </td>
                                                        <td width="251" align="left" valign="middle">
                                                            <div class="contentEditableContainer contentTextEditable">
                                                                
                                                                <div class="contentEditable">
                                                                    <h2 class='white' style="color:#ffffff;font-size:21px;font-weight:normal;">
                                                                        FACTURACI&Oacute;N</h2>                                                                    
                                                                    <ul style="padding-left: 2px; list-style:none;">
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Llegada: <?= date("d/m/Y",  strtotime($this->book['0']['booking_checkin'])); ?></p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Salida: <?= date("d/m/Y",  strtotime($this->book['0']['booking_checkout'])); ?></p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Noches: <?= $this->book['0']['interval']; ?></p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Precio por noche: <?= number_format($this->anuncio['0']['price_ad'],2,",","."); ?> &euro;</p>
                                                                        </li>
                                                                    </ul>
                                                                </div>

                                                                
                                                                
                                                                
                                                                
                                                                
                                                                
                                                                <div class="contentEditable">
                                                                    <h2 class='white' style="color:#ffffff;font-size:21px;font-weight:normal;">
                                                                        &nbsp;</h2>                                                                     
                                                                    <ul style="padding-left: 2px; list-style:none;">
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Alojamiento: <?= number_format($nights*$price,2,",","."); ?> &euro;</p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                           
                                                                            <p>Gastos de tr&aacute;mite: <?= number_format($gastosTramite,2,",","."); ?> &euro;</p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                           
                                                                            <p>Limpieza: <?= number_format($limpieza,2,",","."); ?> &euro;</p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Sub-Total : <?= number_format($subTotal,2,",","."); ?> &euro;</p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>IVA (21%): <?= number_format($subTotal*0.21,2,",","."); ?> &euro;</p>
                                                                        </li>                                                                        
                                                                        
                                                                    </ul>
                                                                </div>
                                                                
                                                                <div class="contentEditable" style="margin-top: 20px;">
                                                                    <h2 class='white' style="color:#ffffff;font-size:21px;font-weight:normal;">
                                                                        TOTAL</h2>                                                                    
                                                                    <ul style="padding-left: 2px; list-style:none;">
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Total alojamiento: <?= number_format($subTotal+$subTotal*0.21,2,",","."); ?> &euro;</p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            
                                                                                
                                                                            <p>Fianza: <?= number_format($fianza,2,",","."); ?> &euro;</p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>&nbsp;</p>
                                                                        </li>
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>&nbsp;</p>
                                                                        </li>
                                                                    </ul>
                                                                </div>
                                                                
                                                                <div class="contentEditable" style="margin-top: 20px;">
                                                                    <h2 class='white' style="color:#ffffff;font-size:21px;font-weight:normal;">
                                                                        TOTAL A PAGAR</h2>
                                                                    <ul style="padding-left: 2px; list-style:none;">
                                                                        <li style="font-size:13px;line-height:19px;">
                                                                            <p>Total alojamiento: <span style="font-weight:bold;"> <?= number_format($subTotal+$subTotal*0.21+$fianza,2,",","."); ?> &euro;</span></p>
                                                                        </li>
                                                                    </ul>
                                                                </div>
                                                                
                                                                
                                                            </div>
                                                        </td>
                                                        <td width="9">
                                                        </td>
                                                    </tr>
                                                    <tr>
                                                        <td colspan="3" height="9">
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>

        <div class="movableContent" style="border: 0px; padding-top: 0px; position: relative;">
            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                <tbody>
                    <tr>
                        <td height="28">
                            <div class="contentEditable" style="width: 75%; float: left;">
                                <p style="color:#000000;font-size:14px;line-height:19px; font-weight: bold; ">
                                    Para la devoluci&oacute;n  de la fianza ver las condiciones anexas. 
                                </p>
                            </div>
                            <div class="contentEditable" style="width: 5%; float: left;">
                                <a target='_blank' href="<?= 'http://localhost/sellers/public' . '/condiciones-legales'; ?>">
                                    <img alt="open in browser image" data-default="placeholder" height="15" src="<?= 'http://localhost/sellers/public' . '/images/openBrowser.png'; ?>" width="15" />
                                </a>
                            </div>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
                      
       <div class="movableContent" style="border: 0px; padding-top: 0px; position: relative;">
            <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%">
                <tr>
                    <td height="30">
                    </td>
                </tr>
                <tr>
                <td bgcolor="#52999E">
                    <table align="center" bgcolor="#52999E" border="0" cellpadding="0" cellspacing="0" width="100%">
                        <tbody>
                            <tr>
                                <td align="left" bgcolor="#52999E" valign="top" width="416">
                                    <table align="center" bgcolor="#52999E" border="0" cellpadding="0" cellspacing="0" width="100%">
                                        <tbody>
                                            <tr>
                                                <td colspan="3" height="28">
                                                </td>
                                            </tr>
                                            <tr>
                                                <td width="30">
                                                </td>
                                                <td valign="middle">
                                                    <div class="contentEditableContainer contentTextEditable">
                                                        <div class="contentEditable">
                                                            <p style="color:#ffffff;font-size:14px;line-height:19px;">
                                                                Cont&aacute;ctanos!</p>
                                                        </div>
                                                    </div>
                                                </td>
                                                <td width="10">
                                                </td>
                                            </tr>
                                            <tr>
                                                <td colspan="3" height="28">
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                                <td align="center" bgcolor="#3C8287" valign="top" width="72">
                                    <table align="center" bgcolor="#3C8287" border="0" cellpadding="0" cellspacing="0" width="100%">
                                        <tbody>
                                            <tr>
                                                <td align="center" bgcolor="#3C8287" height="72" valign="middle" width="72">
                                                    <div class="contentEditableContainer contentFacebookEditable">
                                                        <div class="contentEditable" valign="middle">
                                                            <a target='_blank' href="">
                                                                <img alt="facebook link" data-default="placeholder" data-max-width="37" height="37" src="<?= 'http://localhost/sellers/public' . '/images/facebook.png'; ?>" width="37" data-customIcon="true"/>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                                <td align="center" bgcolor="#275D61" valign="top" width="72">
                                    <table align="center" bgcolor="#275D61" border="0" cellpadding="0" cellspacing="0" height="72" width="100%">
                                        <tbody>
                                            <tr>
                                                <td align="center" bgcolor="#275D61" height="72" valign="middle" width="72">
                                                    <div class="contentEditableContainer contentTwitterEditable">
                                                        <div class="contentEditable" valign="middle">
                                                            <a target='_blank' href="">
                                                                <img alt="twitter link" data-default="placeholder" data-max-width="37" height="37" src="<?= 'http://localhost/sellers/public' . '/images/twitter.png'; ?>" width="37" data-customIcon="true"/>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </td>
                        </tr>
                                        </tbody>
                                </table>
                        </td>
                </tr>
        </table>
        </div>
      
                                                                    </td>
                                                                </tr>
                                                            </tbody>
                                                        </table>
                                                    </td>
                                                    <td valign="top" width="20"></td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </td>
                </tr>
            </tbody>
        </table>
    </body>
</html>
