<style>
    .form-control .btn-select, .form-control .btn-select:hover, .form-control .btn-select:focus {
        font-size: 0.85em;
        
    }    
</style>


<!-- =========== PAGE TITLE ========== -->
<div class="page_title gradient_overlay" style="background: url(images/page_title_bg.jpg);">
    <div class="container">
        <div class="inner">
            <h1>SEO </h1>
            <ol class="breadcrumb">
                <li><a href="<?= $this->baseUrl( ) . '/'; ?>">Home</a></li>
                <li>SEO</li>
            </ol>
        </div>
    </div>
</div>


   <!-- =========== MAIN ========== -->
<main id="booking_page">
    <div class="container">
        <div class="row">

            <div class="col-md-8">
                <div id="booking_advanced">
                    <div class="main_title a_left upper">
                        <h2>SEO - Home</h2>
                    </div>
                    
                    <form id="booking_form_advanced" action="<?= $this->url(array('controller'=>'seo','action'=>'guardar-seo')); ?>" method="post">
                        
                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Title</label>
                                <input id="page-title" name="page-title" type="text" maxlength="90" class="form-control" placeholder="Título de la página" value="<?= $this->seoConfig['0']['title']; ?>"/>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Meta: Description</label>
                                <textarea id="meta-description" class="form-control" name="meta-description" placeholder="Ingrese la meta description ..."><?= $this->seoConfig['0']['description']; ?></textarea>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Meta: Keywords</label>
                                <textarea id="meta-keywords" class="form-control" name="meta-keywords" placeholder="Ingrese las keywords ..."><?= $this->seoConfig['0']['keywords']; ?></textarea>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <div class="form-group">
                                <label>Meta: Author</label>
                                <input id="meta-author" name="meta-author" type="text" maxlength="50" class="form-control" placeholder="Ingrese el author  ..." value="<?= $this->seoConfig['0']['author']; ?>"/>
                            </div>
                        </div>

                        <div class="col-md-12">
                            <button type="submit" class="button btn_blue pull-right"><i class="fa fa-calendar-check-o" aria-hidden="true"></i> GUARDAR </button>
                        </div>

                    </form>
                    
                </div>
            </div>

            
            <div class="col-md-4">
                <div class="special_offers">
                    <div class="main_title a_left upper">
                        <h2>Special Offers</h2>
                    </div>
                    <article class="room mb40">
                        <figure>
                            <a href="room.html" class="hover_effect h_blue h_link">
                                <img src="images/rooms/special1.jpg" class="img-responsive" alt="Image">
                            </a>
                            <figcaption>
                                <h4><a href="room.html">Single Room</a></h4>
                                <div class="price">â‚¬ 89<span> / night</span></div>
                            </figcaption>
                        </figure>
                    </article>
                    <article class="room mb40">
                        <figure>
                            <a href="room.html" class="hover_effect h_blue h_link">
                                <img src="images/rooms/special2.jpg" class="img-responsive" alt="Image">
                            </a>
                            <figcaption>
                                <h4><a href="room.html">Double Room</a></h4>
                                <div class="price">â‚¬ 129<span> / night</span></div>
                            </figcaption>
                        </figure>
                    </article>
                    <article class="room mb40">
                        <figure>
                            <a href="room.html" class="hover_effect h_blue h_link">
                                <img src="images/rooms/special3.jpg" class="img-responsive" alt="Image">
                            </a>
                            <figcaption>
                                <h4><a href="room.html">Delux Room</a></h4>
                                <div class="price">â‚¬ 189<span> / night</span></div>
                            </figcaption>
                        </figure>
                    </article>
                </div>
            </div>
        

            
            
        </div>
    </div>
</main>
            