<script type="text/javascript">   
</script>
<!-- =========== PAGE TITLE ========== -->
<div class="page_title gradient_overlay" style="background: url(images/page_title_bg.jpg);">
    <div class="container">
        <div class="inner">
            <h1>Condiciones Legales</h1>
            <ol class="breadcrumb">
                <li><a href="<?= $this->baseUrl() . '/'; ?>">Home</a></li>
                <li>Condiciones Legales</li>
            </ol>
        </div>
    </div>
</div>
<!-- =========== MAIN ========== -->
<main id="booking_page">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div id="ajax-box">
                    <!-- ========== EX - BOOKING FORM ========== -->
                    <div id="reserva" class="row">
                        <div class="main_title a_left upper room">
                            <figure>
                                <div class="price">
                                    <h2>Condiciones Legales</h2>
                                </div>
                            </figure>
                        </div>
                        <div>
                            &nbsp;
                        </div>
                        <div>
                            &nbsp;
                        </div>
                        <div class="row" style="padding: 16px;">
                            <h2 class="main_title" style="font-weight: bold;">DEPARTAMENTO DE INCIDENCIAS</h2>
                            <p style="font-weight: bold; text-align: justify;">
                                En caso de incidencias puede contactar con la siguiente persona.
                            </p>
                            <p style="font-weight: bold; text-align: justify;">
                                Persona de contacto: Sr. Don Ramón Torres
                            </p>
                            <p style="font-weight: bold; text-align: justify;">
                                E-mail:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;rtorres18@ono.com
                            </p>
                            <p style="font-weight: bold; text-align: justify;">
                                Teléfono:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;685172932
                            </p>
                            <p style="font-weight: bold; text-align: justify;">
                                En el caso, de que delegue a otra persona la estancia del 
                                alojamiento reservado para Ud. deberá notificar el cambio 
                                realizado al departamento de incidencias para obtener la 
                                correspondiente autorización para ello, sin esta autorización,
                                no se realizara la entrega de llaves del alojamiento.
                            </p>
                            <br/>
                            <h2 class="main_title" style="font-weight: bold;">HORA DE ENTRADA Y SALIDA</h2>
                            <p style="font-weight: bold; text-align: justify;">
                                La entrada al alojamiento: será a partir de las 15 horas 
                                del mediodía pudiendo estar 30 minutos antes de la hora 
                                convenida o 30 minutos mas tarde de la hora convenida, en
                                el caso de que surja algún imprevisto y no se pueda cumplir
                                este horario el cliente deberá de ponerse en contacto con 
                                el departamento de incidencias descrito para cambiar el horario
                            </p>
                            <br/>
                            <h2 class="main_title" style="font-weight: bold;">HORA DE ENTRADA Y SALIDA PACTADA</h2>
                            <p style="font-weight: bold; text-align: justify;">
                                También se podrá pactar entre las partes otro horario de 
                                entrada y salida del alojamiento siempre que ambas partes se pongan 
                                de acuerdo para ello a la entrada y salida del alojamiento
                                se verificaran  los enseres que consten en el formulario de entrada y salida.
                            </p>                            
                            <p style="font-weight: bold; text-align: justify;">
                                En el caso de que falte algún objeto del formulario, su 
                                importe se descontara de la fianza a devolver.    
                            </p>
                            <p style="font-weight: bold; text-align: justify;">
                                La fianza será devuelta al cliente mediante la transferencia
                                de su importe a una cuenta corriente del cliente mediante 
                                traspaso con justificante de ingreso    
                            </p>
                            <p style="font-weight: bold; text-align: justify;">
                                El cliente del alojamiento recibirá la factura de su estancia a
                                través de su correo electrónico, o en su correo postal según su
                                elección.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="special_offers">
                    <div class="main_title a_left upper">
                        <h2>Special Offers</h2>
                    </div>
                    <article class="room mb40">
                        <figure>
                            <a href="room.html" class="hover_effect h_blue h_link">
                                <img src="images/rooms/special1.jpg" class="img-responsive" alt="Image">
                            </a>
                            <figcaption>
                                <h4><a href="room.html">Single Room</a></h4>
                                <div class="price">â‚¬ 89<span> / night</span></div>
                            </figcaption>
                        </figure>
                    </article>
                    <article class="room mb40">
                        <figure>
                            <a href="room.html" class="hover_effect h_blue h_link">
                                <img src="images/rooms/special2.jpg" class="img-responsive" alt="Image">
                            </a>
                            <figcaption>
                                <h4><a href="room.html">Double Room</a></h4>
                                <div class="price">â‚¬ 129<span> / night</span></div>
                            </figcaption>
                        </figure>
                    </article>
                    <article class="room mb40">
                        <figure>
                            <a href="room.html" class="hover_effect h_blue h_link">
                                <img src="images/rooms/special3.jpg" class="img-responsive" alt="Image">
                            </a>
                            <figcaption>
                                <h4><a href="room.html">Delux Room</a></h4>
                                <div class="price">â‚¬ 189<span> / night</span></div>
                            </figcaption>
                        </figure>
                    </article>
                </div>
            </div>
        </div>
    </div>
</main>