<div class="page_title gradient_overlay" style="background: url(images/page_title_bg.jpg);">
    <div class="container">
        <div class="inner">
            <h1>Listado</h1>
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->baseUrl() . '/'; ?>">Home</a></li>
                <li>Listado</li>
            </ol>
        </div>
    </div>
</div>
<main class="blog">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <?php foreach ($this->publications as $item) : ?>
                
                <article class="blog_list">
                    <figure>
                        <a href="<?= $this->baseUrl() . '/blog/?id=' . $item["publicationId"]; ?>" class="hover_effect h_link h_blue">
                            <img src="<?= $this->baseUrl() . '/publicaciones/images/57/' . $item["publicationId"] . '/panoramico/' . $item["file_name"] ;?>" class="img-responsive" alt="Image">
                        </a>
                    </figure>
                    <div class="details">
                        <h2><a href="<?= $this->baseUrl() . '/blog/?id=' . $item["publicationId"]; ?>"><?= $item["title_publication"]; ?></a></h2>
                        <div class="info">
                            <span class="meta_part"><a href="#"><i class="fa fa-user"></i>Administrador</a></span>
<!--                            <span class="meta_part"><a href="#"><i class="fa fa-calendar"></i>February 15, 2017</a></span>-->
                            <span class="meta_part"><a href="#"><i class="fa fa-comment-o"></i>68 Comentarios</a></span>
                            <span class="meta_part"><i class="fa fa-folder-open-o"></i><a href="#">Nuevos</a>, <a href="#">Eventos</a></span>
                        </div>
                        <p><?= $item["contenido_publication"]; ?></p>
                        <a class="button btn_blue " href="<?= $this->baseUrl() . '/blog/?id=' . $item["publicationId"]; ?>"><i class="fa fa-angle-double-right"></i> Leer más ... </a>
                    </div>
                </article>
                
                <?php endforeach; ?>
                
                <nav>
                    <ul class="pagination">
                        <li class="prev_pagination"><a href="#"><i class="fa fa-angle-left"></i></a></li>
                        <li class="active"><a href="#">1</a></li>
                        <li><a href="#">2</a></li>
                        <li><a href="#">3</a></li>
                        <li><a href="#">4</a></li>
                        <li><a href="#">5</a></li>
                        <li><a href="#">6</a></li>
                        <li class="next_pagination"><a href="#"><i class="fa fa-angle-right"></i></a></li>
                    </ul>
                </nav>
                
            </div>
            <div class="col-md-3">
                <div class="sidebar">
                    <aside class="widget">
                        <div class="search">
<!--                            <form method="get" class="widget_search">-->
                                <input type="search" placeholder="Búsqueda ...">
                                <button class="search_btn" id="searchsubmit" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
<!--                            </form>-->
                        </div>
                    </aside>
                    <aside class="widget">
                        <h4>CATEGORIAS</h4>
                        <ul class="categories">
                            <li><a href="#">Hotel Zante Rooms <span class="num_posts">51</span></a></li>
                            <li><a href="#">Accommodation <span class="num_posts">24</span></a></li>
                            <li><a href="#">Restaurant <span class="num_posts">9</span></a></li>
                            <li><a href="#">Swimming Pool <span class="num_posts">12</span></a></li>
                            <li><a href="#">Holidays in Greece <span class="num_posts">28</span></a></li>
                            <li><a href="#">Events <span class="num_posts">5</span></a></li>
                            <li><a href="#">News <span class="num_posts">5</span></a></li>
                        </ul>
                    </aside>
<!--                    <aside class="widget">
                        <h4>Latest Posts</h4>
                        <div class="latest_posts">
                            
                            <article class="latest_post">
                                <figure>
                                    <a href="blog-post.html" class="hover_effect h_link h_blue">
                                        <img src="images/blog/thumb1.jpg" alt="Image">
                                    </a>
                                </figure>
                                <div class="details">
                                    <h6><a href="blog-post.html">Live your myth in Greece</a></h6>
                                    <span><i class="fa fa-calendar"></i>23/11/2017</span>
                                </div>
                            </article>
                         
                        </div>
                    </aside>-->
                    <aside class="widget">
                        <h4>Tags</h4>
                        <div class="tagcloud clearfix">
                            <a href="#"><span class="tag">Hotel Zante</span><span class="num">12</span></a>
                            <a href="#"><span class="tag">HOLIDAYS</span><span class="num">24</span></a>
                            <a href="#"><span class="tag">PARTY</span><span class="num">8</span></a>
                            <a href="#"><span class="tag">GREECE</span><span class="num">4</span></a>
                            <a href="#"><span class="tag">PARTY</span><span class="num">56</span></a>
                            <a href="#"><span class="tag">ZAKYNTHOS</span><span class="num">12</span></a>
                        </div>
                    </aside>
                    <aside class="widget">
                        <h4>ARCHIVE</h4>
                        <ul class="archive">
                            <li><a href="#">Marzo 2018<span class="num_posts">21</span></a></li>
                            <li><a href="#">Febrero 2018<span class="num_posts">24</span></a></li>
                            <li><a href="#">Enero 2018<span class="num_posts">38</span></a></li>
                        </ul>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</main>

