<div class="page_title gradient_overlay" style="background: url(images/page_title_bg.jpg);">
    <div class="container">
        <div class="inner">
            <h1>Edición</h1>
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->baseUrl() . '/'; ?>">Home</a></li>
                <li>Edición de imagenes</li>
            </ol>
        </div>
    </div>
</div>


<div style="padding: 40px;">
    <div class="row">
        <div class="col-md-4">    
    
            <form>
                <div id="queue"></div>
                <input id="file_upload" name="file_upload" type="file" multiple="true">
            </form>
        
            <div id="booking_advanced" style="margin-top: 50px;">     
                <form id="booking_form_advanced">
                    <div class="form-group">
                     <div class="form_select">
                    <div style="margin-left: -10px;">
                        <?= $this->gallery; ?>
                    </div>
                    </div>     
                    </div>     
                        <div style="clear:both;"></div>
                    <input id="file_upload_gallery" name="file_upload_gallery" type="file" multiple="true">
                </form>
                
            </div>         

        </div>
    </div>     
</div>
            
            
            
<script type="text/javascript">

    <?php $timestamp = time();?>
    <?php $timestamp2 = time();?>

    $(function() {

         $('#file_upload').uploadify({
         'formData'     : {
                         'timestamp' : '<?php echo $timestamp;?>',
                         'token'     : '<?php echo md5('unique_salt' . $timestamp);?>'
                 },
          'swf'      : '<?php echo $this->baseUrl( ) . "/swf/uploadify.swf";?>',
          'uploader' : '<?php echo $this->baseUrl( ) . "/alta-anuncio/update-upload-pic/?id=" . $this->id;?>',
          'buttonText' : 'Home (imagen: 715x450)',
          'width' : '200'
         });

         $('#file_upload_gallery').uploadify({
         'formData'     : {
                         'timestamp' : '<?php echo $timestamp2;?>',
                         'token'     : '<?php echo md5('unique_salt' . $timestamp2);?>'
                 },
          'swf'      : '<?php echo $this->baseUrl( ) . "/swf/uploadify.swf";?>',
          'uploader' : '<?php echo $this->baseUrl( ) . "/alta-anuncio/update-upload-gallery-pics/?id=" . $this->id;?>',
          'buttonText' : 'Galeria (imagen: 750x400)',
          'width' : '200',
          'onUploadStart' : function() {
              $("#file_upload_gallery").uploadify("settings", 'formData', {'pic' : $("#gallery").val()});
          }                    


         });

    });

</script>
    
    

   
       
   
 
