<nav class="a_center">
    <?php if ($this->pageCount): ?>
    
        <div class="paginationControl">
        <!-- Previous page link -->
        <?php if (isset($this->previous)): ?>
          <!--<a href="<?php echo $this->url(array('page' => $this->previous)); ?>">-->
            <a href="<?php echo $this->baseUrl( ) . '/?page=' . $this->previous ; ?>">   
            &lt; Previous
          </a> |
        <?php else: ?>
          <span class="disabled">&lt; Previous</span> |
        <?php endif; ?>
          
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
          <?php if ($page != $this->current): ?>
      
           <a href="<?php echo $this->baseUrl( ) . '/?page=' . $page ; ?>">
                <?php echo $page; ?>
           </a> |
          <?php else: ?>
            <?php echo $page; ?> |
          <?php endif; ?>
        <?php endforeach; ?>
        
        <!-- Next page link -->
        <?php if (isset($this->next)): ?>
          <!--<a href="<?php echo $this->url(array('page' => $this->next)); ?>">-->
          <a href="<?php echo $this->baseUrl( ) . '/?page=' . $this->next ; ?>">
            Next &gt;
          </a>
        <?php else: ?>
          <span class="disabled">Next &gt;</span>
        <?php endif; ?>
        </div>
    
    <?php endif; ?>
</nav>
    
            <ul class="pagination mt50 mb0">
                <li class="prev_pagination"><a href="#"><i class="fa fa-angle-left"></i></a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">6</a></li>
                <li class="next_pagination"><a href="#"><i class="fa fa-angle-right"></i></a></li>
            </ul>
        
