<nav class="a_center">
    <?php if ($this->pageCount): ?>
    
        <ul class="pagination mt50 mb0">
            <!-- Previous page link -->
            <?php if (isset($this->previous)): ?>
              
               <li class="prev_pagination"><a href="<?php echo $this->baseUrl( ) . '/?page=' . $this->previous ; ?>"><i class="fa fa-angle-left"></i></a></li>
              
              
            <?php else: ?>
              <span class="disabled"></span>
            <?php endif; ?>

            <!-- Numbered page links -->
            <?php foreach ($this->pagesInRange as $page): ?>
              <?php if ($page != $this->current): ?>

                    <li class="active"><a href="<?= $this->baseUrl( ) . '/?page=' . $page ; ?>"><?= $page; ?></a></li>
                    
              <?php else: ?>
                
                    <li><a href="#"><?= $page; ?> </a></li>
                    
              <?php endif; ?>
            <?php endforeach; ?>

            <!-- Next page link -->
            <?php if (isset($this->next)): ?>
              
            <li class="next_pagination"><a href="<?= $this->baseUrl( ) . '/?page=' . $this->next ; ?>"><i class="fa fa-angle-right"></i></a></li>
            
            
            <?php else: ?>
              <span class="disabled"></span>
            <?php endif; ?>
        </ul>
    
    <?php endif; ?>
</nav>