<!-- =========== PAGE TITLE ========== -->
<!--<div class="page_title gradient_overlay" style="background: url(images/page_title_bg.jpg);">
    <div class="container">
        <div class="inner">
            <h1>Listado</h1>
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->baseUrl() . '/'; ?>">Home</a></li>
                <li>Listado</li>
            </ol>
        </div>
    </div>
</div>-->


<div id="classic_slider_euler" class="rev_slider" style="display:none">
    <ul>
        <!-- SLIDE NR. 1 -->
        <li data-transition="crossfade">
            <!-- MAIN IMAGE -->
            <img src="images/slider/slider-1.jpg" 
                 alt="Image" 
                 title="slider_bg2"
                 data-bgposition="center center" 
                 data-bgfit="cover" 
                 data-bgrepeat="no-repeat" 
                 data-bgparallax="10" 
                 class="rev-slidebg" 
                 data-no-retina="">
            <!-- LAYER NR. experimento -->
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="40" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['60','50','40','40']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> VIAJA CON&nbsp;<?= $this->nombre . ' por ' . $this->place1; ?></div>
            
<!--            <div class="tp-caption tp-resizeme"
                 data-x="40" 
                 data-hoffset="" 
                 data-y="80" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['24','50','40','30']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> Alojamiento Hotel
            </div>-->
           
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl() . '/listados'; ?>"
              data-x="40" 
              data-hoffset=""
              data-y="80" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Alojamiento Hotel
            </a>     
            
<!--            <div class="tp-caption tp-resizeme"
                 data-x="40" 
                 data-hoffset="" 
                 data-y="115" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['24','50','40','30']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> Turismo Rural </div>-->

            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="115" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Turismo Rural
            </a>     

                 
                 
<!--            <div class="tp-caption tp-resizeme"
                 data-x="40" 
                 data-hoffset="" 
                 data-y="150" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['24','50','40','30']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> Apartamentos </div>-->
                 
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="150" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Apartamentos
            </a>     
                 


                 
                 
<!--            <div class="tp-caption tp-resizeme"
                 data-x="40" 
                 data-hoffset="" 
                 data-y="185" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['24','50','40','30']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> Alojamiento Privado </div>-->

            <?php if(!empty($this->section1)) : ?>
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="140" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['40','50','40','40']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":2000,"speed":2500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> <?= strtoupper($this->section1); ?></div>
            <?php endif ?>

            <?php if(!empty($this->section2)) : ?>
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="200" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['40','50','40','40']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":3000,"speed":5000,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> <?= strtoupper($this->section2); ?></div>
            <?php endif ?>

            <?php if(!empty($this->section3)) : ?>
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="260" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['40','50','40','40']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":4000,"speed":7500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> <?= strtoupper($this->section3); ?></div>
            <?php endif ?>
            
<!--            <div class="tp-caption tp-resizeme"
                 data-x="40" 
                 data-hoffset="" 
                 data-y="185"
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['24','50','40','30']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> Alojamiento Residencial </div>-->
                 
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="185" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Alojamiento Residencial
            </a>     
                 
                 
                 
                 
<!--            <div class="tp-caption tp-resizeme"
                 data-x="40" 
                 data-hoffset="" 
                 data-y="220" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['24','50','40','30']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> Cruceros </div>-->
                 
                 
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="220" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Cruceros
            </a>     
                 
<!--            <div class="tp-caption tp-resizeme"
                 data-x="40" 
                 data-hoffset="" 
                 data-y="255" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['24','50','40','30']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> Vuelos </div>-->
                 

            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="255" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Vuelos
            </a>     
                 
                 
                 
                 
<!--            <div class="tp-caption tp-resizeme"
                 data-x="40" 
                 data-hoffset="" 
                 data-y="290" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['24','50','40','30']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> Paquetes </div>-->
                 
                 
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="290" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Paquetes
            </a>     
                 
                 
<!--            <div class="tp-caption tp-resizeme"
                 data-x="40" 
                 data-hoffset="" 
                 data-y="325"
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['24','50','40','30']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> Playas </div>-->
                 
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="325" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['22','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Playas
            </a>     

                 
                 
                 
                 
            <!-- LAYER NR. 1 -->
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="395" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['50','50','40','20']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;">DISFRUTA DE TUS VACACIONES!</div>

            <!-- LAYER NR. 2 -->
<!--            <div class="tp-caption tp-resizeme" 
                 data-x="center" 
                 data-hoffset="" 
                 data-y="410" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="16" 
                 data-lineheight="16"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1500,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 6; color: #fff;"> 2 MENSAJE</div>-->
            <!-- LAYER NR. 3 -->
<!--            <div class="tp-caption tp-shape tp-shapewrapper  tp-resizeme"
                 data-x="center" 
                 data-hoffset="-170" 
                 data-y="414"
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-width="['100']" 
                 data-height="['4']"
                 data-transform_idle="o:1;"
                 data-transform_in="x:[175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;s:1500;e:Power3.easeOut;" 
                 data-transform_out="opacity:0;s:500;" 
                 data-mask_in="x:[-100%];y:0;s:inherit;e:inherit;" 
                 data-start="2000"
                 style="z-index: 7;background: url(images/icons/wave_white.svg);"> 
            </div>-->
            <!-- LAYER NR. 4 -->
<!--            <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme" 
                 data-x="center"
                 data-hoffset="-170" 
                 data-y="418" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-width="['100']" 
                 data-height="['4']" 
                 data-transform_idle="o:1;"
                 data-transform_in="x:[175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;s:1500;e:Power3.easeOut;" 
                 data-transform_out="opacity:0;s:500;"
                 data-mask_in="x:[-100%];y:0;s:inherit;e:inherit;"
                 data-start="2100"
                 style="z-index: 7;background: url(images/icons/wave_white.svg);"> </div>-->
            <!-- LAYER NR. 5 -->
<!--            <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme"
                 data-x="center" 
                 data-hoffset="170"
                 data-y="414"
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-width="['100']" 
                 data-height="['4']" 
                 data-transform_idle="o:1;" 
                 data-transform_in="x:[-175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;s:1500;e:Power3.easeOut;" 
                 data-transform_out="opacity:0;s:500;"
                 data-mask_in="x:[100%];y:0;s:inherit;e:inherit;" 
                 data-start="2000" 
                 style="z-index: 7;background: url(images/icons/wave_white.svg);"> </div>-->
            <!-- LAYER NR. 6 -->
<!--            <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme"  
                 data-x="center"
                 data-hoffset="170" 
                 data-y="418" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-width="['100']" 
                 data-height="['4']" 
                 data-transform_idle="o:1;"
                 data-transform_in="x:[-175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;s:1500;e:Power3.easeOut;" 
                 data-transform_out="opacity:0;s:500;" 
                 data-mask_in="x:[100%];y:0;s:inherit;e:inherit;" 
                 data-start="2100"
                 style="z-index: 7;background: url(images/icons/wave_white.svg);"> </div>-->
           <!-- LAYER NR. 7 -->
<!--           <a class="tp-caption button btn_blue" 
              href="<?php echo $this->baseUrl() . '/booking-form/'; ?>"
              data-x="center"
              data-hoffset="-100"
              data-y="480" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="14"
              data-whitespace="nowrap"
              data-frames='[{"delay":2400,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 11;"><i class="fa fa-calendar"></i>BOOK A ROOM NOW
            </a>-->
           <!-- LAYER NR. 8 -->
<!--           <a class="tp-caption button btn_yellow " 
              href="<?php echo $this->baseUrl( ) . '/contact-us/'; ?>"
              data-x="center" 
              data-hoffset="108"
              data-y="480" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="14"
              data-whitespace="nowrap"
              data-frames='[{"delay":2400,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 11;"><i class="fa fa-envelope-o" aria-hidden="true"></i>CONTACT US NOW
            </a>-->
            <!-- LAYER NR. 9 -->
<!--            <div class="tp-caption tp_m_title tp-resizeme" 
                 data-x="center" 
                 data-hoffset="" 
                 data-y="200"
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['18','18','16','16']"
                 data-lineheight="['18','18','16','16']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1800,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i>
                <i class="fa fa-star-o"></i> </div>-->
            <!-- LAYER NR. 10 -->
<!--            <div class="tp-caption tp_m_title tp-resizeme"
                 data-x="center"
                 data-hoffset="" 
                 data-y="240" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['25','25','18','18']" 
                 data-lineheight="['25','25','18','18']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1800,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'>
                3 MENSAJE
            </div>--> </li>
            <!-- SLIDE NR. 2 -->
            <li data-transition="crossfade">
                <!-- MAIN IMAGE -->
                <img src="images/slider/slider-2.jpg" 
                     alt="Image" 
                     title="slider_bg2"
                     data-bgposition="center center"
                     data-bgfit="cover" 
                     data-bgrepeat="no-repeat"
                     data-bgparallax="10"
                     class="rev-slidebg" 
                     data-no-retina="">

            <!-- LAYER NR. experimento -->
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="40" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['60','50','40','40']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> VIAJA CON&nbsp;<?= $this->nombre . ' por ' . $this->place2; ?></div>
            
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl() . '/listados'; ?>"
              data-x="40" 
              data-hoffset=""
              data-y="80" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Alojamiento Hotel
            </a>     

            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="115" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Turismo Rural
            </a>     
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="150" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Apartamentos
            </a>     

            <?php if(!empty($this->section1)) : ?>
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="140" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['40','50','40','40']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":2000,"speed":2500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> <?= strtoupper($this->section1); ?></div>
            <?php endif ?>

            <?php if(!empty($this->section2)) : ?>
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="200" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['40','50','40','40']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":3000,"speed":5000,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> <?= strtoupper($this->section2); ?></div>
            <?php endif ?>

            <?php if(!empty($this->section3)) : ?>
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="260" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['40','50','40','40']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":4000,"speed":7500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> <?= strtoupper($this->section3); ?></div>
            <?php endif ?>

            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="185" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Alojamiento Residencial
            </a>     
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="220" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Cruceros
            </a>     
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="255" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Vuelos
            </a>     
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="290" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Paquetes
            </a>     
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="325" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['22','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Playas
            </a>     
            <!-- LAYER NR. 1 -->
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="395" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['50','50','40','20']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;">DISFRUTA DE TUS VACACIONES!</div>
                
                
                
                
                
                
                
            <!-- LAYER NR. 1 -->
<!--            <div class="tp-caption tp-resizeme" 
                 data-x="center" 
                 data-hoffset="" 
                 data-y="320" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['60','50','40','25']" 
                 data-lineheight="['60','50','40','25']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> MENSAJE 1 </div>-->
            <!-- LAYER NR. 2 -->
<!--            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="410" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="16" 
                 data-lineheight="16"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1500,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 6; color: #fff;"> MENSAJE 2 </div>-->
            <!-- LAYER NR. 3 -->
<!--            <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme" 
                 data-x="center" 
                 data-hoffset="-134" 
                 data-y="414"
                 data-voffset=""
                 data-width="['100']" 
                 data-height="['4']"
                 data-transform_idle="o:1;" 
                 data-transform_in="x:[175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;s:1500;e:Power3.easeOut;"
                 data-transform_out="opacity:0;s:300;" 
                 data-mask_in="x:[-100%];y:0;s:inherit;e:inherit;" 
                 data-start="2000" 
                 data-responsive_offset="on"
                 style="z-index: 7;background: url(images/icons/wave_white.svg);"> </div>-->
            <!-- LAYER NR. 4 -->
<!--            <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme" 
                 data-x="center" 
                 data-hoffset="-134"
                 data-y="418"
                 data-voffset=""
                 data-width="['100']" 
                 data-height="['4']" 
                 data-transform_idle="o:1;" 
                 data-transform_in="x:[175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;s:1500;e:Power3.easeOut;"
                 data-transform_out="opacity:0;s:300;" 
                 data-mask_in="x:[-100%];y:0;s:inherit;e:inherit;"
                 data-start="2100" 
                 data-responsive_offset="on" 
                 style="z-index: 8;background: url(images/icons/wave_white.svg);"> </div>-->
            <!-- LAYER NR. 5 -->
<!--            <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme" 
                 data-x="center" 
                 data-hoffset="134" 
                 data-y="414"
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-width="['100']"
                 data-height="['4']" 
                 data-transform_idle="o:1;" 
                 data-transform_in="x:[-175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;s:1500;e:Power3.easeOut;"
                 data-transform_out="opacity:0;s:300;" 
                 data-mask_in="x:[100%];y:0;s:inherit;e:inherit;" 
                 data-start="2000" 
                 style="z-index: 9;background: url(images/icons/wave_white.svg);"> </div>-->
            <!-- LAYER NR. 6 -->
<!--            <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme" 
                 data-x="center"
                 data-hoffset="134"
                 data-y="418" 
                 data-voffset=""
                 data-width="['100']"
                 data-height="['4']"
                 data-transform_idle="o:1;" 
                 data-transform_in="x:[-175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;s:1500;e:Power3.easeOut;"
                 data-transform_out="opacity:0;s:300;" 
                 data-mask_in="x:[100%];y:0;s:inherit;e:inherit;" 
                 data-start="2100" 
                 data-responsive_offset="on" 
                 style="z-index: 10;background: url(images/icons/wave_white.svg);"> </div>-->
           <!-- LAYER NR. 7 -->
<!--           <a class="tp-caption button btn_yellow" 
              href="booking-form.html"
              data-x="center" 
              data-hoffset="-100"
              data-y="480"
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="14" 
              data-whitespace="nowrap"
              data-frames='[{"delay":2400,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 11;"><i class="fa fa-calendar"></i>BOOK A ROOM NOW</a>  -->
            <!-- LAYER NR. 8 -->
<!--            <a class="tp-caption button btn_yellow "
               href="contact.html"
               data-x="center" 
               data-hoffset="108"
               data-y="480" 
               data-voffset=""
               data-responsive_offset="on" 
               data-fontsize="14" 
               data-frames='[{"delay":2400,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
               style="z-index: 11;"><i class="fa fa-envelope-o" aria-hidden="true"></i>CONTACT US NOW </a>-->
            <!-- LAYER NR. 9 -->
<!--            <div class="tp-caption tp-resizeme" 
                 data-x="center" 
                 data-hoffset="" 
                 data-y="200"
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-frames='[{"delay":1800,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 12;"><img src="images/logo_light.svg" width="200" alt="Image">
            </div>-->
        </li>
                    
                    <!-- SLIDE NR. 3 -->
                    <li data-transition="crossfade">
                        <!-- MAIN IMAGE -->
                        <img src="images/slider/slider-3.jpg" 
                             alt="Image" 
                             title="slider_bg3"
                             data-bgposition="center center"
                             data-bgfit="cover" 
                             data-bgrepeat="no-repeat"
                             data-bgparallax="10" 
                             class="rev-slidebg"
                             data-no-retina="">
                        
            <!-- LAYER NR. experimento -->
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="40" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['60','50','40','40']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> VIAJA CON&nbsp;<?= $this->nombre . ' por ' . $this->place3; ?></div>

            <a class="tp-caption" 
              href="<?php echo $this->baseUrl() . '/listados'; ?>"
              data-x="40" 
              data-hoffset=""
              data-y="80" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Alojamiento Hotel
            </a>     

            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="115" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Turismo Rural
            </a>     
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="150" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Apartamentos
            </a>                      
            <?php if(!empty($this->section1)) : ?>
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="140" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['40','50','40','40']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":2000,"speed":2500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> <?= strtoupper($this->section1); ?></div>
            <?php endif ?>
            
            <?php if(!empty($this->section2)) : ?>
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="200" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['40','50','40','40']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":3000,"speed":5000,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> <?= strtoupper($this->section2); ?></div>
            <?php endif ?>

            <?php if(!empty($this->section3)) : ?>
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="260" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['40','50','40','40']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":4000,"speed":7500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> <?= strtoupper($this->section3); ?></div>
            <?php endif ?>
                 
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="185" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Alojamiento Residencial
            </a>     
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="220" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Cruceros
            </a>     
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="255" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Vuelos
            </a>     
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="290" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Paquetes
            </a>     
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="325" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['22','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Playas
            </a>     
            <!-- LAYER NR. 1 -->
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="395" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['50','50','40','20']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;">DISFRUTA DE TUS VACACIONES!</div>
                        
                        
                        
                        <!-- LAYER NR. 1 -->
<!--                        <div class="tp-caption tp-resizeme" 
                             data-x="center" 
                             data-hoffset="" 
                             data-y="305" 
                             data-voffset=""
                             data-responsive_offset="on" 
                             data-fontsize="['80','70','60','40']" 
                             data-lineheight="['80','70','60','40']"
                             data-whitespace="nowrap"
                             data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                             style="z-index: 5; color: #fff; font-weight: 900;"> MENSAJE 1
                        </div>-->
                        <!-- LAYER NR. 2 -->
<!--                        <div class="tp-caption tp-resizeme" 
                             data-x="center" 
                             data-hoffset=""
                             data-y="410"
                             data-voffset=""
                             data-responsive_offset="on" 
                             data-fontsize="16" 
                             data-lineheight="16"
                             data-whitespace="nowrap"
                             data-frames='[{"delay":1500,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                             style="z-index: 6; color: #fff;"> MENSAJE 2
                        </div>-->
                        <!-- LAYER NR. 3 -->
<!--                        <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme" 
                             data-x="center" 
                             data-hoffset="-180" 
                             data-y="414" 
                             data-voffset=""
                             data-width="['100']" 
                             data-height="['4']" 
                             data-transform_idle="o:1;" 
                             data-transform_in="x:[175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;s:1000;e:Power3.easeOut;" 
                             data-transform_out="opacity:0;s:300;" 
                             data-mask_in="x:[-100%];y:0;s:inherit;e:inherit;"
                             data-start="2300" 
                             data-responsive_offset="on" 
                             style="z-index: 7;background: url(images/icons/wave_white.svg);"> 
                        </div>-->
                        <!-- LAYER NR. 4 -->
<!--                        <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme" 
                             data-x="center"
                             data-hoffset="-180" 
                             data-y="418" 
                             data-voffset=""
                             data-width="['100']" 
                             data-height="['4']" 
                             data-transform_idle="o:1;" 
                             data-transform_in="x:[175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;s:1000;e:Power3.easeOut;" 
                             data-transform_out="opacity:0;s:300;"
                             data-mask_in="x:[-100%];y:0;s:inherit;e:inherit;" 
                             data-start="2400" 
                             data-responsive_offset="on" 
                             style="z-index: 8;background: url(images/icons/wave_white.svg);"> 
                        </div>-->
                        <!-- LAYER NR. 5 -->
<!--                        <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme" 
                             data-x="center"
                             data-hoffset="180"
                             data-y="414" 
                             data-voffset=""
                             data-width="['100']"
                             data-height="['4']" 
                             data-transform_idle="o:1;" 
                             data-transform_in="x:[-175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;s:1000;e:Power3.easeOut;" 
                             data-transform_out="opacity:0;s:300;" data-mask_in="x:[100%];y:0;s:inherit;e:inherit;" 
                             data-start="2300" 
                             data-responsive_offset="on" 
                             style="z-index: 9;background: url(images/icons/wave_white.svg);">
                        </div>-->
                        <!-- LAYER NR. 6 -->
<!--                        <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme" 
                             data-x="center" 
                             data-hoffset="180"
                             data-y="418" 
                             data-voffset=""
                             data-width="['100']" 
                             data-height="['4']" 
                             data-transform_idle="o:1;" 
                             data-transform_in="x:[-175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;s:1000;e:Power3.easeOut;" 
                             data-transform_out="opacity:0;s:300;" 
                             data-mask_in="x:[100%];y:0;s:inherit;e:inherit;" 
                             data-start="2400" 
                             data-responsive_offset="on" 
                             style="z-index: 10;background: url(images/icons/wave_white.svg);"> 
                        </div>-->
                    </li>
                    
                    
                    <!-- SLIDE NR. 4 -->
                    <li data-transition="crossfade">
                        <!-- MAIN IMAGE -->
                        <img src="images/slider/slider-4.jpg" 
                             alt="Image" 
                             title="slider_bg3"
                             data-bgposition="center center"
                             data-bgfit="cover" 
                             data-bgrepeat="no-repeat"
                             data-bgparallax="10" 
                             class="rev-slidebg"
                             data-no-retina="">
                        
            <!-- LAYER NR. experimento -->
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="40" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['60','50','40','40']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> VIAJA CON&nbsp;<?= $this->nombre . ' por ' . $this->place4; ?> </div>
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl() . '/listados'; ?>"
              data-x="40" 
              data-hoffset=""
              data-y="80" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Alojamiento Hotel
            </a>     

            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="115" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Turismo Rural
            </a>     
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="150" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Apartamentos
            </a>
            <?php if(!empty($this->section1)) : ?>
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="140" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['40','50','40','40']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":2000,"speed":2500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> <?= strtoupper($this->section1); ?></div>
            <?php endif ?>
            
            <?php if(!empty($this->section2)) : ?>
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="200" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['40','50','40','40']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":3000,"speed":5000,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> <?= strtoupper($this->section2); ?></div>
            <?php endif ?>

            <?php if(!empty($this->section3)) : ?>
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="260" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['40','50','40','40']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":4000,"speed":7500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;"> <?= strtoupper($this->section3); ?></div>
            <?php endif ?>

            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="185" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Alojamiento Residencial
            </a>     
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="220" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Cruceros
            </a>     
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="255" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Vuelos
            </a>     
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="290" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['24','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Paquetes
            </a>     
            <a class="tp-caption" 
              href="<?php echo $this->baseUrl(); ?>"
              data-x="40" 
              data-hoffset=""
              data-y="325" 
              data-voffset=""
              data-responsive_offset="on" 
              data-fontsize="['22','50','40','30']"
              data-lineheight="['60','50','40','30']"
              data-whitespace="nowrap"
              data-frames='[{"delay":1200,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
              style="z-index: 5; color: #fff; font-weight: 900;">Playas
            </a>     
            <!-- LAYER NR. 1 -->
            <div class="tp-caption tp-resizeme"
                 data-x="center" 
                 data-hoffset="" 
                 data-y="395" 
                 data-voffset=""
                 data-responsive_offset="on" 
                 data-fontsize="['50','50','40','20']" 
                 data-lineheight="['60','50','40','30']"
                 data-whitespace="nowrap"
                 data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","to":"o:1;","ease":"Power3.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                 style="z-index: 5; color: #fff; font-weight: 900;">DISFRUTA DE TUS VACACIONES!</div>
                        
                        
                        
                        <!-- LAYER NR. 1 -->
                        <!-- leves [DESKTOP, LAPTOP, TABLET, SMARTPHONE] -->
<!--                        <div class="tp-caption tp-resizeme" 
                             data-x="center" 
                             data-hoffset="" 
                             data-y="305" 
                             data-voffset=""
                             data-responsive_offset="on" 
                             data-fontsize="['60','70','60','40']"  
                             data-lineheight="['80','70','60','40']"
                             data-whitespace="nowrap"
                             data-frames='[{"delay":1000,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                             style="z-index: 5; color: #fff; font-weight: 900;"> DISFRUTA DE TUS VACACIONES
                        </div>-->
                        
                        <!-- LAYER NR. 2 -->
<!--                        <div class="tp-caption tp-resizeme" 
                             data-x="center" 
                             data-hoffset=""
                             data-y="410"
                             data-voffset=""
                             data-responsive_offset="on" 
                             data-fontsize="16" 
                             data-lineheight="16"
                             data-whitespace="nowrap"
                             data-frames='[{"delay":1500,"speed":1500,"frame":"0","from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:0;","mask":"x:0px;y:[100%];s:inherit;e:inherit;","to":"o:1;","ease":"Power2.easeInOut"},{"delay":"wait","speed":500,"frame":"999","to":"auto:auto;","ease":"Power3.easeInOut"}]'
                             style="z-index: 6; color: #fff;"> MENSAJE 2
                        </div>-->
                        <!-- LAYER NR. 3 -->
<!--                        <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme" 
                             data-x="center" 
                             data-hoffset="-180" 
                             data-y="414" 
                             data-voffset=""
                             data-width="['100']" 
                             data-height="['4']" 
                             data-transform_idle="o:1;" 
                             data-transform_in="x:[175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;s:1000;e:Power3.easeOut;" 
                             data-transform_out="opacity:0;s:300;" 
                             data-mask_in="x:[-100%];y:0;s:inherit;e:inherit;"
                             data-start="2300" 
                             data-responsive_offset="on" 
                             style="z-index: 7;background: url(images/icons/wave_white.svg);"> 
                        </div>-->
                        <!-- LAYER NR. 4 -->
<!--                        <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme" 
                             data-x="center"
                             data-hoffset="-180" 
                             data-y="418" 
                             data-voffset=""
                             data-width="['100']" 
                             data-height="['4']" 
                             data-transform_idle="o:1;" 
                             data-transform_in="x:[175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;s:1000;e:Power3.easeOut;" 
                             data-transform_out="opacity:0;s:300;"
                             data-mask_in="x:[-100%];y:0;s:inherit;e:inherit;" 
                             data-start="2400" 
                             data-responsive_offset="on" 
                             style="z-index: 8;background: url(images/icons/wave_white.svg);"> 
                        </div>-->
                        <!-- LAYER NR. 5 -->
<!--                        <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme" 
                             data-x="center"
                             data-hoffset="180"
                             data-y="414" 
                             data-voffset=""
                             data-width="['100']"
                             data-height="['4']" 
                             data-transform_idle="o:1;" 
                             data-transform_in="x:[-175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;s:1000;e:Power3.easeOut;" 
                             data-transform_out="opacity:0;s:300;" data-mask_in="x:[100%];y:0;s:inherit;e:inherit;" 
                             data-start="2300" 
                             data-responsive_offset="on" 
                             style="z-index: 9;background: url(images/icons/wave_white.svg);">
                        </div>-->
                        <!-- LAYER NR. 6 -->
<!--                        <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme" 
                             data-x="center" 
                             data-hoffset="180"
                             data-y="418" 
                             data-voffset=""
                             data-width="['100']" 
                             data-height="['4']" 
                             data-transform_idle="o:1;" 
                             data-transform_in="x:[-175%];y:0px;z:0;rX:0;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;opacity:1;s:1000;e:Power3.easeOut;" 
                             data-transform_out="opacity:0;s:300;" 
                             data-mask_in="x:[100%];y:0;s:inherit;e:inherit;" 
                             data-start="2400" 
                             data-responsive_offset="on" 
                             style="z-index: 10;background: url(images/icons/wave_white.svg);"> 
                        </div>-->
                    </li>

                   
                </ul>
</div>



<!-- =========== MAIN ========== -->
<main id="rooms_list">

   <div class="container">
      <!-- ITEM -->
      
      <?php foreach($this->ads as $ad) : ?>
      <article class="room_list">
         <div class="row row-flex">
            <div class="col-lg-4 col-md-5 col-sm-12">
                <?php $file = (empty($ad["file_home"]))?$ad["file_name"]:$ad["file_home"]; ?>
               <figure>
                   <a href="<?php echo $this->baseUrl( ) . '/habitacion/' . $ad["url"]; ?>" class="hover_effect h_link h_blue">
                       <img src="<?= $this->baseUrl( ) . '/ads/images/57/'. $ad["id"] . '/home/' . $file; ?>" class="img-responsive" alt="Image">
                   </a>
               </figure>
            </div>
            <div class="col-lg-8 col-md-7 col-sm-12">
               <div class="room_details row-flex">
                  <div class="col-md-9 col-sm-9 col-xs-12 room_desc">
                     <h3><a href="<?php echo $this->baseUrl( ) . '/habitacion/' . $ad["url"]; ?>"> <?= $ad["title_ad"]; ?> </a></h3>
                         <p>
                            <?= $ad["comments_ad"]; ?>
                         </p>
                     <div class="room_services">
                        <i class="fa fa-coffee" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Breakfast Included" data-original-title="Breakfast"></i> 
                         <i class="fa fa-cutlery" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Restaurant" data-original-title="Zante Restaurant"></i> 
                     </div>
                  </div>
                  <div class="col-md-3 col-sm-3 col-xs-12 room_price">
                     <div class="room_price_inner">
                        <span class="room_price_number"> €<?= number_format($ad["price_ad"],0); ?> </span>
                        <small class="upper"> por noche </small>
                        <a href="<?php echo $this->baseUrl( ) . '/booking-form/' . $ad["url"]; ?>" class="button  btn_blue btn_full upper">Reservar!</a>
                     </div>
                  </div>
               </div>
            </div>
         </div>
    </article>
    <?php endforeach; ?>
    <!-- ITEM -->
<!--    <article class="room_list">
     <div class="row">
        <div class="col-lg-4 col-md-5 col-sm-12">
           <figure>
              <div class="room_list_slider owl-carousel">
                 <div class="item">                                                 
                    <a href="<?php echo $this->baseUrl( ) . '/habitacion/'; ?>" class="hover_effect h_link h_blue"><img src="<?php echo $this->baseUrl( ) . '/images/rooms/double1.jpg';?>" alt="Image"></a>
                 </div>
                 <div class="item">
                    <a href="<?php echo $this->baseUrl( ) . '/habitacion/'; ?>" class="hover_effect h_link h_blue"><img src="<?php echo $this->baseUrl( ) . '/images/rooms/double2.jpg';?>" alt="Image"></a>
                 </div>
                 <div class="item">
                    <a href="<?php echo $this->baseUrl( ) . '/habitacion/'; ?>" class="hover_effect h_link h_blue"><img src="<?php echo $this->baseUrl( ) . '/images/rooms/double3.jpg';?>" alt="Image"></a>
                 </div>
              </div>
           </figure>
        </div>
            <div class="col-lg-8 col-md-7 col-sm-12">
               <div class="room_details">
                  <div class="col-md-9 col-sm-9 col-xs-12 room_desc">
                     <h3><a href="<?php echo $this->baseUrl( ) . '/habitacion/'; ?>"> Double Room - With Slider </a></h3>
                     <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam.</p>
                     <div class="room_services">
                         <i class="fa fa-coffee" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Breakfast Included" data-original-title="Breakfast"></i> 
                         <i class="fa fa-cutlery" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Restaurant" data-original-title="Zante Restaurant"></i>
                         <i class="fa fa-television" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Plasma TV with cable Channel" data-original-title="Plasma TV"></i>
                     </div>
                  </div>
                  <div class="col-md-3 col-sm-3 col-xs-12 room_price">
                     <div class="room_price_inner">
                        <span class="room_price_number"> €129,00  </span>
                        <small class="upper"> per night </small>
                        <a href="<?php echo $this->baseUrl( ) . '/habitacion/'; ?>" class="button  btn_blue btn_full upper">Book Now</a>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </article>-->
      <!-- ITEM -->
<!--      <article class="room_list">
         <div class="row">
            <div class="col-lg-4 col-md-5 col-sm-12">
               <figure>
                  <a href="room.html" class="hover_effect h_link h_blue">
                  <img src="images/rooms/delux.jpg" class="img-responsive" alt="Image">
                  </a>
               </figure>
            </div>
            <div class="col-lg-8 col-md-7 col-sm-12">
               <div class="room_details">
                  <div class="col-md-9 col-sm-9 col-xs-12 room_desc">
                     <h3><a href="room.html"> Delux Room </a></h3>
                     <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam.</p>
                     <div class="room_services">
                        <i class="fa fa-coffee" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Breakfast Included" data-original-title="Breakfast"></i>
                        <i class="fa fa-wifi" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Free WiFi" data-original-title="WiFi"></i>
                        <i class="fa fa-cutlery" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Restaurant" data-original-title="Zante Restaurant"></i>
                        <i class="fa fa-television" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Plasma TV with cable Channel" data-original-title="Plasma TV"></i>
                     </div>
                  </div>
                  <div class="col-md-3 col-sm-3 col-xs-12 room_price">
                     <div class="room_price_inner">
                        <span class="room_price_number"> €189,00  </span>
                        <small class="upper"> per night </small>
                        <a href="room.html" class="button  btn_blue btn_full upper">Book Now</a>
                     </div>
                  </div>
                       </div>
                    </div>
                 </div>
              </article>-->
              <!-- ITEM -->
<!--              <article class="room_list">
                 <div class="row">
                    <div class="col-lg-4 col-md-5 col-sm-12">
                       <figure>
                          <a href="room.html" class="hover_effect h_link h_blue">
                          <img src="images/rooms/king.jpg" class="img-responsive" alt="Image">
                          </a>
                       </figure>
                    </div>
                    <div class="col-lg-8 col-md-7 col-sm-12">
                       <div class="room_details">
                          <div class="col-md-9 col-sm-9 col-xs-12 room_desc">
                             <h3><a href="room.html"> King Room </a></h3>
                             <p> Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam.</p>
                             <div class="room_services">
                                 <i class="fa fa-coffee" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Breakfast Included" data-original-title="Breakfast"></i> 
                                 <i class="fa fa-cutlery" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Restaurant" data-original-title="Zante Restaurant"></i>
                                <i class="fa fa-television" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Plasma TV with cable Channel" data-original-title="Plasma TV"></i>
                             </div>
                          </div>
                          <div class="col-md-3 col-sm-3 col-xs-12 room_price">
                             <div class="room_price_inner">
                                <span class="room_price_number"> €219,00  </span>
                                <small class="upper"> per night </small>
                                <a href="room.html" class="button  btn_blue btn_full upper">Book Now</a>
                             </div>
                          </div>
                       </div>
                    </div>
                 </div>
              </article>-->
              <!-- ITEM -->
<!--              <article class="room_list">
                 <div class="row">
                    <div class="col-lg-4 col-md-5 col-sm-12">
                       <figure>
                          <a href="room.html" class="hover_effect h_link h_blue">
                          <img src="images/rooms/honeymoon.jpg" class="img-responsive" alt="Image">
                          </a>
                       </figure>
                    </div>
                    <div class="col-lg-8 col-md-7 col-sm-12">
                       <div class="room_details">
                          <div class="col-md-9 col-sm-9 col-xs-12 room_desc">
                             <h3><a href="room.html">Honeymoon Room </a></h3>
                             <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam.</p>
                             <div class="room_services">
                                 <i class="fa fa-coffee" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Breakfast Included" data-original-title="Breakfast"></i> 
                                <i class="fa fa-cutlery" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Restaurant" data-original-title="Zante Restaurant"></i>
                                <i class="fa fa-television" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Plasma TV with cable Channel" data-original-title="Plasma TV"></i>
                             </div>
                          </div>
                          <div class="col-md-3 col-sm-3 col-xs-12 room_price">
                             <div class="room_price_inner">
                                <span class="room_price_number"> €289,00  </span>
                                <small class="upper"> per night </small>
                                <a href="room.html" class="button  btn_blue btn_full upper">Book Now</a>
                             </div>
                          </div>
                       </div>
                    </div>
                 </div>
              </article>-->
              <!-- ITEM -->
<!--              <article class="room_list">
                 <div class="row">
                    <div class="col-lg-4 col-md-5 col-sm-12">
                       <figure>
                          <a href="room.html" class="hover_effect h_link h_blue">
                          <img src="images/rooms/family.jpg" class="img-responsive" alt="Image">
                          </a>
                       </figure>
                    </div>
                    <div class="col-lg-8 col-md-7 col-sm-12">
                       <div class="room_details">
                          <div class="col-md-9 col-sm-9 col-xs-12 room_desc">
                             <h3><a href="room.html"> Family Room </a></h3>
                             <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam.</p>
                             <div class="room_services">
                                 <i class="fa fa-coffee" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Breakfast Included" data-original-title="Breakfast"></i> 
                                 <i class="fa fa-cutlery" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Restaurant" data-original-title="Zante Restaurant"></i>
                                <i class="fa fa-television" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="Plasma TV with cable Channel" data-original-title="Plasma TV"></i>
                             </div>
                          </div>
                          <div class="col-md-3 col-sm-3 col-xs-12 room_price">
                             <div class="room_price_inner">
                                <span class="room_price_number"> €149,00  </span>
                                <small class="upper"> per night </small>
                                <a href="room.html" class="button  btn_blue btn_full upper">Book Now</a>
                             </div>
                          </div>
                       </div>
                    </div>
                 </div>
              </article>-->
            
<!--      <nav class="a_center">
            <ul class="pagination mt50 mb0">
                <li class="prev_pagination"><a href="#"><i class="fa fa-angle-left"></i></a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">6</a></li>
                <li class="next_pagination"><a href="#"><i class="fa fa-angle-right"></i></a></li>
            </ul>
      </nav>-->

   </div>
</main>