<script type="text/javascript">   
    $(document).ready(function() {
        
         $(':input[type="submit"]').prop('disabled', false);
         
        
    });
</script>

<style>
    #booking_form_advanced textarea.form-control {
        height: 80px;
    }
</style>

<!-- =========== PAGE TITLE ========== -->
<div class="page_title gradient_overlay" style="background: url(images/page_title_bg.jpg);">
    <div class="container">
        <div class="inner">
            <h1>Datos Facturación</h1>
            <ol class="breadcrumb">
                <li><a href="<?= $this->baseUrl() . '/'; ?>">Home</a></li>
                <li>Datos Facturación</li>
            </ol>
        </div>
    </div>
</div>

<!-- =========== MAIN ========== -->
<main id="booking_page">
    <div class="container">
        <div class="row">
           
            <div class="col-md-8">
                <div id="ajax-box">

                    <div class="main_title a_left upper">
                        <h2>Datos Facturación</h2>
                    </div>
                    <!-- ========== BOOKING FORM ========== -->
                    <div id="ajax-box-booking_advanced" class="row">
                        <form id="booking_form_advanced" action="<?= $this->baseUrl() . '/booking-form/reserva'; ?>" method="post">
                            
                            <input id="anuncioId" name="anuncioId" type="hidden" value="<?= $this->anuncioId; ?>" /> 
                            <input id="bookingId" name="bookingId" type="hidden" value="<?= $this->bookingId; ?>" /> 
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Nombre/Razón Social</label>
                                    <input id="billingName" name="billingName" type="text" class="form-control" placeholder="Ingrese nombre/razón social">
                                </div>
                            </div>
                            <div class="clearfix"></div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>NIE/NIF</label>
                                    <input id="billingDocument" name="billingDocument" type="text" class="form-control" placeholder="Ingrese NIE/NIF">
                                </div>
                            </div>
 
                            <div class="clearfix"></div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Teléfono</label>
                                    <input id="billingPhone" name="billingPhone" type="text" class="form-control" placeholder="Ingrese teléfono">
                                </div>
                            </div>
                             
                            <div class="clearfix"></div>
                             

                           <div class="col-md-12">
                                <div class="form-group">
                                    <label>Dirección de facturación</label>
                                    <textarea id="billingAddress" class="form-control" name="billingAddress" placeholder="Ingrese la dirección ..."></textarea>
                                </div>
                            </div>
  
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Código Postal</label>
                                    <input id="billingZip" name="billingZip" type="text" class="form-control" placeholder="Código postal"/>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Población</label>
                                    <input id="billingCity" name="billingCity" type="text" class="form-control" placeholder="Población"/>
                                </div>
                            </div>
      
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Provincia</label>
                                    <input id="billingProvincia" name="billingProvincia" type="text" class="form-control" placeholder="Provincia"/>
                                </div>
                            </div>
                            
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label>Pais</label>
                                    <div class="form_select">
                                        <select id="billingCountry" name="billingCountry" class="form-control" title="Seleccione tu pais" data-header="Seleccione tu pais" data-live-search="true" data-size="5">
                                            <option value="82">Alemania</option>
                                            <option value="206">España</option>
                                            <option value="232">Estados Unidos</option>
                                            <option value="75">Francia</option>
                                            <option value="231">Reino Unido</option>
                                            <option value="107">Italia</option>
                                            <option value="1">Afghanistan</option>
                                            <option value="2">Albania</option>
                                            <option value="3">Algeria</option>
                                            <option value="4">American Samoa</option>
                                            <option value="5">Andorra</option>
                                            <option value="6">Angola</option>
                                            <option value="7">Anguilla</option>
                                            <option value="8">Antigua &amp; Barbuda</option>
                                            <option value="9">Argentina</option>
                                            <option value="10">Armenia</option>
                                            <option value="11">Aruba</option>
                                            <option value="12">Australia</option>
                                            <option value="13">Austria</option>
                                            <option value="14">Azerbaijan</option>
                                            <option value="15">Bahamas</option>
                                            <option value="16">Bahrain</option>
                                            <option value="17">Bangladesh</option>
                                            <option value="18">Barbados</option>
                                            <option value="19">Belarus</option>
                                            <option value="20">Belgium</option>
                                            <option value="21">Belize</option>
                                            <option value="22">Benin</option>
                                            <option value="23">Bermuda</option>
                                            <option value="24">Bhutan</option>
                                            <option value="25">Bolivia</option>
                                            <option value="26">Bonaire</option>
                                            <option value="27">Bosnia &amp; Herzegovina</option>
                                            <option value="28">Botswana</option>
                                            <option value="29">Brazil</option>
                                            <option value="30">British Indian Ocean Ter</option>
                                            <option value="31">Brunei</option>
                                            <option value="32">Bulgaria</option>
                                            <option value="33">Burkina Faso</option>
                                            <option value="34">Burundi</option>
                                            <option value="35">Cambodia</option>
                                            <option value="36">Cameroon</option>
                                            <option value="37">Canada</option>
                                            <option value="38">Canary Islands</option>
                                            <option value="39">Cape Verde</option>
                                            <option value="40">Cayman Islands</option>
                                            <option value="41">Central African Republic</option>
                                            <option value="42">Chad</option>
                                            <option value="43">Channel Islands</option>
                                            <option value="44">Chile</option>
                                            <option value="45">China</option>
                                            <option value="46">Christmas Island</option>
                                            <option value="47">Cocos Island</option>
                                            <option value="48">Colombia</option>
                                            <option value="49">Comoros</option>
                                            <option value="50">Congo</option>
                                            <option value="51">Cook Islands</option>
                                            <option value="52">Costa Rica</option>
                                            <option value="53">Cote D'Ivoire</option>
                                            <option value="54">Croatia</option>
                                            <option value="55">Cuba</option>
                                            <option value="56">Curacao</option>
                                            <option value="57">Cyprus</option>
                                            <option value="58">Czech Republic</option>
                                            <option value="59">Denmark</option>
                                            <option value="60">Djibouti</option>
                                            <option value="61">Dominica</option>
                                            <option value="62">Dominican Republic</option>
                                            <option value="63">East Timor</option>
                                            <option value="64">Ecuador</option>
                                            <option value="65">Egypt</option>
                                            <option value="66">El Salvador</option>
                                            <option value="67">Equatorial Guinea</option>
                                            <option value="68">Eritrea</option>
                                            <option value="69">Estonia</option>
                                            <option value="70">Ethiopia</option>
                                            <option value="71">Falkland Islands</option>
                                            <option value="72">Faroe Islands</option>
                                            <option value="73">Fiji</option>
                                            <option value="74">Finland</option>
                                            <option value="76">French Guiana</option>
                                            <option value="77">French Polynesia</option>
                                            <option value="78">French Southern Ter</option>
                                            <option value="79">Gabon</option>
                                            <option value="80">Gambia</option>
                                            <option value="81">Georgia</option>
                                            <option value="83">Ghana</option>
                                            <option value="84">Gibraltar</option>
                                            <option value="85">Great Britain</option>
                                            <option value="86">Greece</option>
                                            <option value="87">Greenland</option>
                                            <option value="88">Grenada</option>
                                            <option value="89">Guadeloupe</option>
                                            <option value="90">Guam</option>
                                            <option value="91">Guatemala</option>
                                            <option value="92">Guinea</option>
                                            <option value="93">Guyana</option>
                                            <option value="94">Haiti</option>
                                            <option value="95">Hawaii</option>
                                            <option value="96">Honduras</option>
                                            <option value="97">Hong Kong</option>
                                            <option value="98">Hungary</option>
                                            <option value="99">Iceland</option>
                                            <option value="100">India</option>
                                            <option value="101">Indonesia</option>
                                            <option value="102">Iran</option>
                                            <option value="103">Iraq</option>
                                            <option value="104">Ireland</option>
                                            <option value="105">Isle of Man</option>
                                            <option value="106">Israel</option>
                                            <option value="107">Italy</option>
                                            <option value="108">Jamaica</option>
                                            <option value="109">Japan</option>
                                            <option value="110">Jordan</option>
                                            <option value="111">Kazakhstan</option>
                                            <option value="112">Kenya</option>
                                            <option value="113">Kiribati</option>
                                            <option value="114">Korea North</option>
                                            <option value="115">Korea South</option>
                                            <option value="116">Kuwait</option>
                                            <option value="117">Kyrgyzstan</option>
                                            <option value="118">Laos</option>
                                            <option value="119">Latvia</option>
                                            <option value="120">Lebanon</option>
                                            <option value="121">Lesotho</option>
                                            <option value="122">Liberia</option>
                                            <option value="123">Libya</option>
                                            <option value="124">Liechtenstein</option>
                                            <option value="125">Lithuania</option>
                                            <option value="126">Luxembourg</option>
                                            <option value="127">Macau</option>
                                            <option value="128">Macedonia</option>
                                            <option value="129">Madagascar</option>
                                            <option value="130">Malaysia</option>
                                            <option value="131">Malawi</option>
                                            <option value="132">Maldives</option>
                                            <option value="133">Mali</option>
                                            <option value="134">Malta</option>
                                            <option value="135">Marshall Islands</option>
                                            <option value="136">Martinique</option>
                                            <option value="137">Mauritania</option>
                                            <option value="138">Mauritius</option>
                                            <option value="139">Mayotte</option>
                                            <option value="140">Mexico</option>
                                            <option value="141">Midway Islands</option>
                                            <option value="142">Moldova</option>
                                            <option value="143">Monaco</option>
                                            <option value="144">Mongolia</option>
                                            <option value="145">Montserrat</option>
                                            <option value="146">Morocco</option>
                                            <option value="147">Mozambique</option>
                                            <option value="148">Myanmar</option>
                                            <option value="149">Nambia</option>
                                            <option value="150">Nauru</option>
                                            <option value="151">Nepal</option>
                                            <option value="152">Netherland Antilles</option>
                                            <option value="153">Netherlands (Holland, Europe)</option>
                                            <option value="154">Nevis</option>
                                            <option value="155">New Caledonia</option>
                                            <option value="156">New Zealand</option>
                                            <option value="157">Nicaragua</option>
                                            <option value="158">Niger</option>
                                            <option value="159">Nigeria</option>
                                            <option value="160">Niue</option>
                                            <option value="161">Norfolk Island</option>
                                            <option value="162">Norway</option>
                                            <option value="163">Oman</option>
                                            <option value="164">Pakistan</option>
                                            <option value="165">Palau Island</option>
                                            <option value="166">Palestine</option>
                                            <option value="167">Panama</option>
                                            <option value="168">Papua New Guinea</option>
                                            <option value="169">Paraguay</option>
                                            <option value="170">Peru</option>
                                            <option value="171">Philippines</option>
                                            <option value="172">Pitcairn Island</option>
                                            <option value="173">Poland</option>
                                            <option value="174">Portugal</option>
                                            <option value="175">Puerto Rico</option>
                                            <option value="176">Qatar</option>
                                            <option value="177">Republic of Montenegro</option>
                                            <option value="178">Republic of Serbia</option>
                                            <option value="179">Reunion</option>
                                            <option value="180">Romania</option>
                                            <option value="181">Russia</option>
                                            <option value="182">Rwanda</option>
                                            <option value="182">St Barthelemy</option>
                                            <option value="183">St Eustatius</option>
                                            <option value="184">St Helena</option>
                                            <option value="185">St Kitts-Nevis</option>
                                            <option value="186">St Lucia</option>
                                            <option value="187">St Maarten</option>
                                            <option value="188">St Pierre &amp; Miquelon</option>
                                            <option value="189">St Vincent &amp; Grenadines</option>
                                            <option value="190">Saipan</option>
                                            <option value="191">Samoa</option>
                                            <option value="192">Samoa American</option>
                                            <option value="193">San Marino</option>
                                            <option value="194">Sao Tome &amp; Principe</option>
                                            <option value="195">Saudi Arabia</option>
                                            <option value="196">Senegal</option>
                                            <option value="197">Serbia</option>
                                            <option value="198">Seychelles</option>
                                            <option value="199">Sierra Leone</option>
                                            <option value="200">Singapore</option>
                                            <option value="201">Slovakia</option>
                                            <option value="202">Slovenia</option>
                                            <option value="203">Solomon Islands</option>
                                            <option value="204">Somalia</option>
                                            <option value="205">South Africa</option>
                                            <option value="207">Sri Lanka</option>
                                            <option value="208">Sudan</option>
                                            <option value="209">Suriname</option>
                                            <option value="210">Swaziland</option>
                                            <option value="211">Sweden</option>
                                            <option value="212">Switzerland</option>
                                            <option value="213">Syria</option>
                                            <option value="214">Tahiti</option>
                                            <option value="215">Taiwan</option>
                                            <option value="216">Tajikistan</option>
                                            <option value="217">Tanzania</option>
                                            <option value="218">Thailand</option>
                                            <option value="219">Togo</option>
                                            <option value="220">Tokelau</option>
                                            <option value="221">Tonga</option>
                                            <option value="222">Trinidad &amp; Tobago</option>
                                            <option value="223">Tunisia</option>
                                            <option value="224">Turkey</option>
                                            <option value="225">Turkmenistan</option>
                                            <option value="226">Turks &amp; Caicos Is</option>
                                            <option value="227">Tuvalu</option>
                                            <option value="228">Uganda</option>
                                            <option value="229">Ukraine</option>
                                            <option value="230">United Arab Emirates</option>
                                            <option value="233">Uruguay</option>
                                            <option value="234">Uzbekistan</option>
                                            <option value="235">Vanuatu</option>
                                            <option value="236">Vatican City State</option>
                                            <option value="237">Venezuela</option>
                                            <option value="238">Vietnam</option>
                                            <option value="239">Virgin Islands (Brit)</option>
                                            <option value="240">Virgin Islands (USA)</option>
                                            <option value="241">Wake Island</option>
                                            <option value="242">Wallis &amp; Futana Is</option>
                                            <option value="243">Yemen</option>
                                            <option value="244">Zaire</option>
                                            <option value="245">Zambia</option>
                                            <option value="246">Zimbabwe</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-12">
<!--                                <button type="button" class="button btn_blue pull-right" onclick="saveBook();"> <i class="fa fa-calendar-check-o" aria-hidden="true"></i> RESERVAR </button>-->
                                <button class="button btn_lg btn_blue btn_full" type="submit"> RESERVAR</button>
                            </div>
                            
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="special_offers">
                    <div class="main_title a_left upper">
                        <h2>Special Offers</h2>
                    </div>
                    <article class="room mb40">
                        <figure>
                            <a href="room.html" class="hover_effect h_blue h_link">
                                <img src="images/rooms/special1.jpg" class="img-responsive" alt="Image">
                            </a>
                            <figcaption>
                                <h4><a href="room.html">Single Room</a></h4>
                                <div class="price">â‚¬ 89<span> / night</span></div>
                            </figcaption>
                        </figure>
                    </article>
                    <article class="room mb40">
                        <figure>
                            <a href="room.html" class="hover_effect h_blue h_link">
                                <img src="images/rooms/special2.jpg" class="img-responsive" alt="Image">
                            </a>
                            <figcaption>
                                <h4><a href="room.html">Double Room</a></h4>
                                <div class="price">â‚¬ 129<span> / night</span></div>
                            </figcaption>
                        </figure>
                    </article>
                    <article class="room mb40">
                        <figure>
                            <a href="room.html" class="hover_effect h_blue h_link">
                                <img src="images/rooms/special3.jpg" class="img-responsive" alt="Image">
                            </a>
                            <figcaption>
                                <h4><a href="room.html">Delux Room</a></h4>
                                <div class="price">â‚¬ 189<span> / night</span></div>
                            </figcaption>
                        </figure>
                    </article>
                </div>
            </div>
        </div>
    </div>
</main>