<script type="text/javascript">   
</script>


<!-- =========== PAGE TITLE ========== -->
<div class="page_title gradient_overlay" style="background: url(images/page_title_bg.jpg);">
    <div class="container">
        <div class="inner">
            <h1>Reserva Aceptada</h1>
            <ol class="breadcrumb">
                <li><a href="<?= $this->baseUrl() . '/'; ?>">Home</a></li>
                <li>Reserva Aceptada</li>
            </ol>
        </div>
    </div>
</div>


   <!-- =========== MAIN ========== -->
<main id="booking_page">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div id="ajax-box">
                    <!-- ========== EX - BOOKING FORM ========== -->
                    <div id="reserva" class="row">
                        <div class="main_title a_left upper room">
                            <figure>
                                <div class="price">
                                    <h2>Reserva Aceptada</h2>
                                </div>
                            </figure>
                        </div>
                        <div>
                            &nbsp;
                        </div>
                        <div>
                            &nbsp;
                        </div>                    
    
                        <div class="row" style="padding: 16px;">
                            <p style="font-weight: bold;">
                            Durante algunos minutos va a recibir un correo electrónico ...
                            </p>
                            
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="special_offers">
                    <div class="main_title a_left upper">
                        <h2>Special Offers</h2>
                    </div>
                    <article class="room mb40">
                        <figure>
                            <a href="room.html" class="hover_effect h_blue h_link">
                                <img src="images/rooms/special1.jpg" class="img-responsive" alt="Image">
                            </a>
                            <figcaption>
                                <h4><a href="room.html">Single Room</a></h4>
                                <div class="price">â‚¬ 89<span> / night</span></div>
                            </figcaption>
                        </figure>
                    </article>
                    <article class="room mb40">
                        <figure>
                            <a href="room.html" class="hover_effect h_blue h_link">
                                <img src="images/rooms/special2.jpg" class="img-responsive" alt="Image">
                            </a>
                            <figcaption>
                                <h4><a href="room.html">Double Room</a></h4>
                                <div class="price">â‚¬ 129<span> / night</span></div>
                            </figcaption>
                        </figure>
                    </article>
                    <article class="room mb40">
                        <figure>
                            <a href="room.html" class="hover_effect h_blue h_link">
                                <img src="images/rooms/special3.jpg" class="img-responsive" alt="Image">
                            </a>
                            <figcaption>
                                <h4><a href="room.html">Delux Room</a></h4>
                                <div class="price">â‚¬ 189<span> / night</span></div>
                            </figcaption>
                        </figure>
                    </article>
                </div>
            </div>

        </div>
    </div>
</main>