<!-- =========== PAGE TITLE ========== -->
<div class="page_title gradient_overlay" style="background: url(images/page_title_bg.jpg);">
    <div class="container">
        <div class="inner">
            <h1>Photo Gallery</h1>
            <ol class="breadcrumb">
                <li><a href="<?= $this->baseUrl( ) . '/'; ?>">Home</a></li>
                <li>Photo Gallery</li>
            </ol>
        </div>
    </div>
</div>
        

<!-- =========== MAIN ========== -->
<main id="gallery_page_style_2">
    <div class="container">
        <div class="row">
            <div class="image-gallery">
                <!-- ITEM -->
                <div class="col-md-3 col-sm-6">
                    <figure>
                        <a href="<?= $this->baseUrl() .  '/images/gallery/gallery1.jpg'; ?>" class="hover_effect h_lightbox h_blue">
                            <img src="<?= $this->baseUrl() .  '/images/gallery/gallery1.jpg'; ?>" class="img-responsive" alt="Image">
                        </a>
                    </figure>
                </div>
                <!-- ITEM -->
                <div class="col-md-3 col-sm-6">
                    <figure>
                        <a href="<?= $this->baseUrl() .  '/images/gallery/gallery2.jpg'; ?>" class="hover_effect h_lightbox h_blue">
                            <img src="<?= $this->baseUrl() .  '/images/gallery/gallery2.jpg'; ?>" class="img-responsive" alt="Image">
                        </a>
                    </figure>
                </div>
                <!-- ITEM -->
                <div class="col-md-3 col-sm-6">
                    <figure>
                        <a href="<?= $this->baseUrl() .  '/images/gallery/gallery3.jpg'; ?>" class="hover_effect h_lightbox h_blue">
                            <img src="<?= $this->baseUrl() .  '/images/gallery/gallery3.jpg'; ?>" class="img-responsive" alt="Image">
                        </a>
                    </figure>
                </div>
                <!-- ITEM -->
                <div class="col-md-3 col-sm-6">
                    <figure>
                        <a href="<?= $this->baseUrl() .  '/images/gallery/gallery4.jpg'; ?>" class="hover_effect h_lightbox h_blue">
                            <img src="<?= $this->baseUrl() .  '/images/gallery/gallery4.jpg'; ?>" class="img-responsive" alt="Image">
                        </a>
                    </figure>
                </div>
                <!-- ITEM -->
                <div class="col-md-3 col-sm-6">
                    <figure>
                        <a href="<?= $this->baseUrl() .  '/images/gallery/gallery5.jpg'; ?>" class="hover_effect h_lightbox h_blue">
                            <img src="<?= $this->baseUrl() .  '/images/gallery/gallery5.jpg'; ?>" class="img-responsive" alt="Image">
                        </a>
                    </figure>
                </div>
                <!-- ITEM -->
                <div class="col-md-3 col-sm-6">
                    <figure>
                        <a href="<?= $this->baseUrl() .  '/images/gallery/gallery6.jpg'; ?>" class="hover_effect h_lightbox h_blue">
                            <img src="<?= $this->baseUrl() .  '/images/gallery/gallery6.jpg'; ?>" class="img-responsive" alt="Image">
                        </a>
                    </figure>
                </div>
                <!-- ITEM -->
                <div class="col-md-3 col-sm-6">
                    <figure>
                        <a href="<?= $this->baseUrl() .  '/images/gallery/gallery7.jpg'; ?>" class="hover_effect h_lightbox h_blue">
                            <img src="<?= $this->baseUrl() .  '/images/gallery/gallery7.jpg'; ?>" class="img-responsive" alt="Image">
                        </a>
                    </figure>
                </div>
                <!-- ITEM -->
                <div class="col-md-3 col-sm-6">
                    <figure>
                        <a href="<?= $this->baseUrl() .  '/images/gallery/gallery8.jpg'; ?>" class="hover_effect h_lightbox h_blue">
                            <img src="<?= $this->baseUrl() .  '/images/gallery/gallery8.jpg'; ?>" class="img-responsive" alt="Image">
                        </a>
                    </figure>
                </div>
                <!-- ITEM -->
                <div class="col-md-3 col-sm-6">
                    <figure>
                        <a href="<?= $this->baseUrl() .  '/images/gallery/gallery9.jpg'; ?>" class="hover_effect h_lightbox h_blue">
                            <img src="<?= $this->baseUrl() .  '/images/gallery/gallery9.jpg'; ?>" class="img-responsive" alt="Image">
                        </a>
                    </figure>
                </div>
                <!-- ITEM -->
                <div class="col-md-3 col-sm-6">
                    <figure>
                        <a href="<?= $this->baseUrl() .  '/images/gallery/gallery10.jpg'; ?>" class="hover_effect h_lightbox h_blue">
                            <img src="<?= $this->baseUrl() .  '/images/gallery/gallery10.jpg'; ?>" class="img-responsive" alt="Image">
                        </a>
                    </figure>
                </div>
                <!-- ITEM -->
                <div class="col-md-3 col-sm-6">
                    <figure>
                        <a href="<?= $this->baseUrl() .  '/images/gallery/gallery11.jpg'; ?>" class="hover_effect h_lightbox h_blue">
                            <img src="<?= $this->baseUrl() .  '/images/gallery/gallery11.jpg'; ?>" class="img-responsive" alt="Image">
                        </a>
                    </figure>
                </div>
                <!-- ITEM -->
                <div class="col-md-3 col-sm-6">
                    <figure>
                        <a href="<?= $this->baseUrl() .  '/images/gallery/gallery12.jpg'; ?>" class="hover_effect h_lightbox h_blue">
                            <img src="<?= $this->baseUrl() .  '/images/gallery/gallery12.jpg'; ?>" class="img-responsive" alt="Image">
                        </a>
                    </figure>
                </div>
                
            </div>
        </div>
    </div>
</main>
        