<style>
    .item-thumbnail-home {
        height: 40px;
        width: 50px;
        float: left;
        margin-left: 3px;
    }
</style>
<?php 
    if(APPLICATION_ENV=='development') {
        $baseUrl = $this->baseUrl();
    }elseif(APPLICATION_ENV=='production') {
        $baseUrl = 'http://www.turisdays.com';
    }
?>

<?php //foreach($this->ads as $ad) : ?>
    <article class="room_list">
        <div class="row row-flex">
            <div class="col-lg-4 col-md-5 col-sm-12">
                <?php $file = (empty($this->file_home))?$this->file_name:$this->file_home; ?>
                <figure>
                    <a title="<?= $this->titulo_enlace; ?>" href="<?= $baseUrl . '/hotel/' . $this->url; ?>" class="hover_effect h_link h_blue">
                        <img title="<?= $this->titulo_imagen; ?>" src="<?= $baseUrl . '/ads/empleos/58/'. $this->id . '/home/' . $file; ?>" class="img-responsive" alt="<?= $ad['alt_imagen']; ?>">
                    </a>
                </figure>
            </div>
            <div class="col-lg-8 col-md-7 col-sm-12">
                <div class="room_details row-flex">
                    
                    <div class="col-md-9 col-sm-9 col-xs-12 room_desc">
                        
                        <h3><a title="<?= $this->titulo_enlace; ?>"  href="<?= $baseUrl . '/hotel/' . $this->url; ?>"> <?= $this->titulo_empleo; ?> </a></h3>
                        <p>
                            <a title="<?= $this->titulo_enlace; ?>"  href="<?= $baseUrl . '/hotel/' . $this->url; ?>"> <?= $this->localidad . ' - ' . $this->provincia; ?> </a>
                        </p>
                        <p>
                        
                                <?= Application_Model_System_Util::myTruncate($this->contenido_seo, 140, " ", " ... ");  ?>
                           
                            <a title="<?= $this->titulo_enlace; ?>"  href="<?= $baseUrl . '/hotel/' . $this->url; ?>"> ¡Leer más! </a>
                        </p>
                        <div>
                            <a title="<?= $this->titulo_enlace; ?>" href="<?= $baseUrl . '/hotel/' . $this->url; ?>" class="button  btn_blue upper" style="width:96%;">
                                <?= '¡'. $this->titulo_oferta . '!'; ?>
                            </a>
                        </div>
                        <?php if(false): ?>
                        <div class="room_services">
                            <?php $counter = 0; ?>
                            <?php foreach($this->serviceicons as $key => $service) : ?>
                                <?php if($service===1 && $counter <7) : ?>
                                    <a title="<?= $this->titulo_enlace; ?>" href="<?= $baseUrl . '/hotel/' . $this->url; ?>">    
                                        <i class="fa <?= $key; ?>" data-toggle="popover" data-placement="top" data-trigger="hover" data-content="<?= $this->messageicons[$key]; ?>" data-original-title="Servicio"></i> 
                                    </a>
                                    <?php $counter++; ?>
                                <?php endif; ?>
                            <?php endforeach; ?>
                        </div>
                        <?php endif; ?>

                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-12 room_price">
                        <div class="room_price_inner">
                        <span class="room_price_number">  </span>
                        <a title="<?= $this->titulo_enlace; ?>"  href="<?= $baseUrl . '/hotel/' . $this->url; ?>">
                            <small class="upper"> Interesados </small>
                        </a>
                        <a title="<?= $this->titulo_enlace; ?>" href="<?= $baseUrl . '/hotel/' . $this->url; ?>" class="button  btn_blue btn_full upper">¡Aplicar!</a>
                        </div>
                    </div>
                    
                </div>
            </div>
            
            <div class="col-lg-12 col-md-12 col-sm-24">
                <!-- Item #1 --> 
<!--                <div class="item-thumbnail-home">
                    <a title="<?= $this->titulo_enlace; ?>" href="<?= $baseUrl; ?>">    
                        <img class="img-responsive" 
                             src="<?php //echo $this->baseUrl( ) . '/ads/empleos/58/36/home-thumbnail/single-room27.jpg';?>" alt="Image" height="4" width="5">
                    </a>
                </div>-->
                <?php if(count($this->thumbailpics)>0): ?>
                <?php foreach($this->thumbailpics as $pic): ?>
                <div class="item-thumbnail-home">
                    <a title="<?= $this->titulo_enlace; ?>" href="<?= $baseUrl . '/hotel/' . $this->url; ?>">    
                        <img class="img-responsive" 
                             src="<?php echo $this->baseUrl( ) . '/ads/empleos/58/' . $pic['empleo_id']  . '/home-thumbnail/' . $pic['file_name'];?>" alt="Image" height="4" width="5">
                    </a>
                </div>
                <?php endforeach; ?>
                <?php endif; ?>
            </div>
         </div>
    </article>
<?php //endforeach; ?>