<!-- =========== MAIN ========== -->
<main id="rooms_list">
    <?php if(count($this->adsUpdated)>0) : ?>
    <div class="page_title gradient_overlay" style="background: url(images/page_title_bg.jpg);">
        <div class="container">
            <div class="inner">
                <h1>Edición de Hoteles</h1>
                <ol class="breadcrumb">
                    <li><a href="<?php echo $this->baseUrl( ) . '/'; ?>">Home</a></li>
                    <li>Edición</li>
                </ol>
            </div>
        </div>
    </div>
    <?php endif; ?>

    <div class="container">
    <!-- ITEM -->
    <?php if(count($this->adsUpdated)>0) : ?>
    
        <?php foreach($this->adsUpdated as $ad) : ?>
            <article class="room_list">
                <div class="row row-flex">
                    <div class="col-lg-4 col-md-5 col-sm-12">
                        <?php $file = (empty($ad["file_home"]))?$ad["file_name"]:$ad["file_home"]; ?>
                        <figure>
                            <a href="<?php echo $this->baseUrl() . '/validacion/hotel/?id=' . $ad["id"]; ?>" class="hover_effect h_link h_blue">
                                <img src="<?= $this->baseUrl() . '/ads/hoteles/58/'. $ad["id"] . '/home/' . $file; ?>" class="img-responsive" alt="Image">
                            </a>
                        </figure>
                    </div>
                    <div class="col-lg-8 col-md-7 col-sm-12">
                        <div class="room_details">
                            <div class="col-md-9 col-sm-9 col-xs-12 room_desc">
                                <h3><a href="<?php echo $this->baseUrl( ) . '/validacion/hotel/?id=' . $ad["id"]; ?>"> <?= $ad["titulo_anuncio"]; ?> </a></h3>
                            </div>
                            <div class="col-md-6 col-sm-6 col-xs-12">
                                <div style="margin-top:4px;">
                                    <a href="<?php echo $this->baseUrl() . '/validacion/hotel/?id=' . $ad["id"]; ?>" class="button  btn_blue btn_full upper">Editar!</a>
                                </div>
                                <div style="margin-top:4px;">
                                    <a href="<?php echo $this->baseUrl() . '/validacion/hotel-change-image/?id=' . $ad["id"]; ?>" class="button  btn_blue btn_full upper">Imagenes!</a>
                                </div>
                                <div style="margin-top:4px;">
                                    <a href="<?php echo $this->baseUrl() . '/validacion/hotel-desactivar/?id=' . $ad["id"] . '&estado=' . $ad['activo']; ?>" class="button  btn_<?= ($ad['activo'])?'blue':'yellow';?> btn_full upper"><?= ($ad["activo"])?'Desactivar!':'Activar!';?></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </article>
        <?php endforeach; ?>

        <nav class="a_center">
            <ul class="pagination mt50 mb0">
                <li class="prev_pagination"><a href="#"><i class="fa fa-angle-left"></i></a></li>
                <li class="active"><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li><a href="#">6</a></li>
                <li class="next_pagination"><a href="#"><i class="fa fa-angle-right"></i></a></li>
            </ul>
        </nav>
    
    <?php endif; ?>
    
    </div>    
    
</main>
