<div>
    <form>
         <div id="queue"></div>
        <input id="file_upload" name="file_upload" type="file" multiple="true">
    </form>
    
    <script type="text/javascript">
        <?php $timestamp = time();?>
       
        $(function() {
            $('#file_upload').uploadify({
                'formData' : {
                             'timestamp' : '<?php echo $timestamp;?>',
                             'token'     : '<?php echo md5('unique_salt' . $timestamp);?>'
                     },
                'swf'      : '<?php echo $this->baseUrl() . "/swf/uploadify.swf";?>',
                'uploader' : '<?php echo $this->baseUrl() . "/alta-publicacion/execute-upload-pic";?>',
                'buttonText' : 'Panorámico 1170 X 600',
                'width' : '200'
            });
        });
        
    </script>
</div>

       
       
   
 
   