<div class="page_title gradient_overlay" style="background: url(images/page_title_bg.jpg);">
    <div class="container">
        <div class="inner">
            <h1>Comentarios</h1>
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->baseUrl( ) . '/'; ?>">Home</a></li>
                <li>Comentario</li>
                <li>Ingrese su comentario</li>
            </ol>
        </div>
    </div>
</div>




<!-- =========== MAIN ========== -->
<main id="contact_page_style_2">
    
    <div class="container">
        <div class="row">

            <div class="col-md-8">
                <div class="main_title  a_left">
                    <h2> COMENTARIO </h2>
                </div>
                <form id="contact-form-page" method="post" action="<?= $this->url(array('controller'=>'comentario','action'=>'send-comment')); ?>">
                    <div class="row">
                        
                        <div class="form-group col-md-6 col-sm-6">
                            <label>Tipo de viaje</label>
                            <div class="form_select">
                                <select id="travel-type" name="travel-type" class="form-control" title="Seleccionar tipo de viaje" data-header="Tipo de viaje">
                                    <option value="1" data-subtext="<span class='label label-info'></span>">Turismo</option>
                                    <option value="2" data-subtext="<span class='label label-info'></span>">Vacaciones</option>
                                    <option value="3" data-subtext="<span class='label label-info'></span>">Negocio</option>
                                </select>
                            </div>
                        </div>

                        <div class="clearfix"></div>

                        <div class="form-group col-md-6 col-sm-6">
                            <label>Puntuar</label>
                            <div class="form_select">
                                <select id="point" name="point" class="form-control" title="Seleccionar tipo de alojamiento" data-header="Tipo de alojamiento">
                                    <option value="0" data-subtext="<span class='label label-info'></span>">Sin estrella</option>
                                    <option value="1" data-subtext="<span class='label label-info'></span>">1 estrella</option>
                                    <option value="2" data-subtext="<span class='label label-info'></span>">2 estrellas</option>
                                    <option value="3" data-subtext="<span class='label label-info'></span>">3 estrellas</option>
                                    <option value="4" data-subtext="<span class='label label-info'></span>">4 estrellas</option>
                                    <option value="5" data-subtext="<span class='label label-info'></span>">5 estrellas</option>
                                </select>
                            </div>
                        </div>
                        
                        <input type="hidden" id="anuncio-id" name="anuncio-id" value="42"/>
                        
                        <div class="form-group col-md-12 col-sm-12 col-xs-12">
                            <label class="control-label">Si quieres opinar, deja un comentario sobre el alojamiento.</label>
                            <textarea class="form-control" id="comment" name="comment" placeholder="Tu comentario ..."></textarea>
                        </div>
                        
                        <div class="form-group col-md-12 col-sm-12 col-xs-12">
                            <button type="submit" class="button  btn_blue mt35 upper pull-right"> <i class="fa fa-paper-plane-o" aria-hidden="true"></i> Comentar </button>
                        </div>

                    </div>
                </form>
            </div>

            <div class="col-md-4">
                <div id="contact-page22">
                    <ul class="contact-info upper mt40">
                        <li>
                            <span class="ci_item">EMAIL:</span>
                            admin@viajacon.es
                        </li>
                        <li>
                            <span class="ci_item">WEB:</span>
                            www.viajacon.es
                        </li>
                        <li>
                            <span class="ci_item">TELÉFONO:</span>
                            +1 (34) <strong>123456789</strong>
                        </li>
                    </ul>
                    <div class="social_media">
                        <a class="facebook" href="#"><i class="fa fa-facebook"></i></a>
                        <a class="twitter" href="#"><i class="fa fa-twitter"></i></a>
                        <a class="googleplus" href="#"><i class="fa fa-google-plus"></i></a>
                        <a class="pinterest" href="#"><i class="fa fa-pinterest"></i></a>
                        <a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a>
                        <a class="youtube" href="#"><i class="fa fa-youtube"></i></a>
                        <a class="instagram" href="#"><i class="fa fa-instagram"></i></a>
                    </div>
                </div>
            </div>

        </div>
    </div>

</main>
