<div class="page_title gradient_overlay" style="background: url(images/page_title_bg.jpg);">
    <div class="container">
        <div class="inner">
            <h1>Blog Post</h1>
            <ol class="breadcrumb">
                <li><a href="<?php echo $this->baseUrl( ) . '/'; ?>">Home</a></li>
                <li>Blog</li>
                <li>Blog Post</li>
            </ol>
        </div>
    </div>
</div>
<main>
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <article class="blog_post">
                    <figure>
                        <a href="<?php echo $this->baseUrl() . '/publicaciones/images/57/' . $this->publication["publicationId"] . '/panoramico/' . $this->publication["file_name"] ;?>" class="hover_effect h_lightbox h_blue" data-rel="magnific-popup">
                            <img src="<?php echo $this->baseUrl() . '/publicaciones/images/57/' . $this->publication["publicationId"] . '/panoramico/' . $this->publication["file_name"] ;?>" class="img-responsive" alt="Image">
                        </a>
                    </figure>
                    <div class="details">
                        <h2><a href="blog-post.html"><?= $this->publication["title_publication"] ;?></a></h2>
                        <div class="info">
                            <span class="meta_part"><a href="#"><i class="fa fa-user"></i> Administrador</a></span>
<!--                            <span class="meta_part"><a href="#"><i class="fa fa-calendar"></i>February 15, 2017</a></span>-->
                            <span class="meta_part"><a href="#"><i class="fa fa-comment-o"></i>68 Comentarios</a></span>
                            <span class="meta_part"><i class="fa fa-folder-open-o"></i><a href="#">Nuevos</a>, <a href="#">Eventos</a></span>
                        </div>
                        <p><?= $this->publication["contenido_publication"] ;?></p>
<!--                        <p>Zril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum. Typi non habent claritatem insitam; est usus legentis in iis qui facit eorum claritatem. Investigationes demonstraverunt lectores legere me lius quod ii legunt saepius. Claritas est etiam processus dynamicus, qui sequitur.</p>-->
                        <blockquote>
                            <i class="fa fa-quote-left"></i>
                            <span class="quote_text"><?= $this->publication["blockquote"] ;?></span>
                        </blockquote>
                        <p> <?= $this->publication["contenido_publication_2"] ;?> </p>
                        <div class="meta_post">
                            <div class="tags">
                                <span><i class="fa fa-tags"></i> TAGS</span>
                                <a href="#" rel="tag">Greece</a>
                                <a href="#" rel="tag">Holidays</a>
                                <a href="#" rel="tag">Zakynthos</a>
                            </div>
                            <div class="share">
                                <span><i class="fa fa-share-alt"></i> SHARE</span>
                                <div class="social_media">
                                    <a class="facebook" href="#" data-toggle="tooltip" data-original-title="Facebook"><i class="fa fa-facebook"></i></a>
                                    <a class="twitter" href="#" data-toggle="tooltip" data-original-title="Twitter"><i class="fa fa-twitter"></i></a>
                                    <a class="googleplus" href="#" data-toggle="tooltip" data-original-title="Google Plus"><i class="fa fa-google-plus"></i></a>
                                    <a class="pinterest" href="#" data-toggle="tooltip" data-original-title="Pinterest"><i class="fa fa-pinterest"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </article>
<!--                        <div class="comments">
                            <div class="main_title t_style3">
                                <h2>COMMENTS (4)</h2>
                            </div>
                            <ol class="comments_list clearfix">
                                <li class="comment single_comment">
                                    
                                    <div class="comment-container comment-box">
                                        <a href="#" class="avatar">
                                            <img width="80" height="80" src="images/users/user1.jpg" alt="Image">
                                        </a>
                                        <div class="comment_content">
                                            <h4 class="author_name"><a href="#">John Doe</a></h4>
                                            <a href="#comment-form" class="reply_link">Reply</a>
                                            <span class="comment_info">
                                              <i class="fa fa-calendar"></i>
                                              <a href="#">
                                                 <time datetime="2017-10-01T19:56:36+00:00">October 1, 2017 at 7:56 pm</time>
                                              </a>
                                            </span>
                                            <div class="comment_said_text">
                                                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                                            </div>
                                        </div>
                                    </div>
                                    <ol class="children">
                                        <li class="comment single_comment">
                                            
                                            <div class="comment-box">
                                                <a href="#" class="avatar">
                                                    <img width="80" height="80" src="images/users/user2.jpg" alt="Image">
                                                </a>
                                                <div class="comment_content">
                                                    <h4 class="author_name"><a href="#">Ina Aldrich</a></h4>
                                                    <a href="#comment-form" class="reply_link">Reply</a>
                                                    <span class="comment_info">
                                                        <i class="fa fa-calendar"></i>
                                                        <a href="#">
                                                            <time datetime="2017-10-01T19:56:36+00:00">August 1, 2017 at 10:56 pm</time>
                                                        </a>
                                                    </span>
                                                    <div class="comment_said_text">
                                                        <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <ol class="children">
                                                <li class="comment single_comment">
                                                    
                                                    <div class="comment-box">
                                                        <a href="#" class="avatar">
                                                            <img width="80" height="80" src="images/users/user3.jpg" alt="Image">
                                                        </a>
                                                        <div class="comment_content">
                                                            <h4 class="author_name"><a href="#">William Whiten</a></h4>
                                                            <a href="#comment-form" class="reply_link">Reply</a>
                                                            <span class="comment_info">
                                                                <i class="fa fa-calendar"></i>
                                                                <a href="#">
                                                                    <time datetime="2017-10-01T19:56:36+00:00">October 1, 2017 at 7:56 pm</time>
                                                                </a>
                                                            </span>
                                                            <div class="comment_said_text">
                                                                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <ol class="children">
                                                        <li class="comment single_comment">

                                                        </li>
                                                    </ol>
                                                </li>
                                            </ol>
                                        </li>
                                    </ol>
                                </li>
                                <li class="comment single_comment">
                                   
                                    <div class="comment-box">
                                        <a href="#" class="avatar">
                                            <img width="80" height="80" src="images/users/user4.jpg" alt="Image">
                                        </a>
                                        <div class="comment_content">
                                            <h4 class="author_name"><a href="#">Amy Ellison</a></h4>
                                            <a href="#comment-form" class="reply_link">Reply</a>
                                            <span class="comment_info">
                                                <i class="fa fa-calendar"></i>
                                                <a href="#">
                                                    <time datetime="2017-10-01T19:56:36+00:00">October 1, 2017 at 7:56 pm</time>
                                                </a>
                                            </span>
                                            <div class="comment_said_text">
                                                <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat.</p>
                                            </div>
                                        </div>
                                    </div>
                                </li>
                            </ol>
                            <div class="main_title mt40">
                                <h2>LEAVE YOUR COMMENT</h2>
                            </div>
                            <div class="row">
                                <form id="comment-form" class="comment-form">
                                    <div class="col-md-6">
                                        <input type="text" class="form-control" placeholder="Name"> </div>
                                    <div class="col-md-6">
                                        <input type="email" class="form-control" placeholder="Email"> </div>
                                    <div class="col-md-12">
                                        <textarea class="form-control" placeholder="Write Your Comment"></textarea>
                                    </div>
                                    <div class="col-md-12">
                                        <button class="button  btn_blue pull-right"><i class="fa fa-paper-plane-o"></i> POST YOUR COMMENT </button>
                                        <span class="a_left">*Your email address will not be published.</span>
                                    </div>
                                </form>
                            </div>
                        </div> -->
                    </div>
                    <div class="col-md-3">
                        <div class="sidebar">
                            <aside class="widget">
                                <div class="search">
<!--                                    <form method="get" class="widget_search">-->
                                        <input type="search" placeholder="Búsqueda ...">
                                        <button class="search_btn" id="searchsubmit" type="submit">
                                            <i class="fa fa-search"></i>
                                        </button>
<!--                                    </form>-->
                                </div>
                            </aside>
                            <aside class="widget">
                                <h4>CATEGORIAS</h4>
                                <ul class="categories">
                                    <li><a href="#">Hotel Zante Rooms <span class="num_posts">51</span></a></li>
                                    <li><a href="#">Accommodation <span class="num_posts">24</span></a></li>
                                    <li><a href="#">Restaurant <span class="num_posts">9</span></a></li>
                                    <li><a href="#">Swimming Pool <span class="num_posts">12</span></a></li>
                                    <li><a href="#">Holidays in Greece <span class="num_posts">28</span></a></li>
                                    <li><a href="#">Events <span class="num_posts">5</span></a></li>
                                    <li><a href="#">News <span class="num_posts">5</span></a></li>
                                </ul>
                            </aside>
                            <aside class="widget">
                                <h4> Últimas Publicaciones </h4>
                                <div class="latest_posts">

                                    <?php foreach($this->publications as $item) : ?>
                                    <article class="latest_post">
                                        <figure>
                                            <a href="<?php echo $this->baseUrl() . '/blog/' . $item["url"]; ?>" class="hover_effect h_link h_blue">
                                                <img src="<?php echo $this->baseUrl() . '/publicaciones/images/57/' . $item["publicationId"] . '/thumbnail/' . $item["file_name"] ;?>" alt="Image">
                                            </a>
                                        </figure>
                                        <div class="details">
                                            <h6><a href="<?php echo $this->baseUrl() . '/blog/' . $item["url"]; ?>"><?= $item["title_publication"]; ?></a></h6>
                                            <span><i class="fa fa-calendar"></i><?= $item["created_date"]; ?></span>
                                        </div>
                                    </article>
                                    <?php  endforeach; ?>

                        </div>
                    </aside>
                    <aside class="widget">
                        <h4>Tags</h4>
                        <div class="tagcloud clearfix">
                            <a href="#"><span class="tag">Hotel Zante</span><span class="num">12</span></a>
                            <a href="#"><span class="tag">HOLIDAYS</span><span class="num">24</span></a>
                            <a href="#"><span class="tag">PARTY</span><span class="num">8</span></a>
                            <a href="#"><span class="tag">GREECE</span><span class="num">4</span></a>
                            <a href="#"><span class="tag">PARTY</span><span class="num">56</span></a>
                            <a href="#"><span class="tag">ZAKYNTHOS</span><span class="num">12</span></a>
                        </div>
                    </aside>
                    <aside class="widget">
                        <h4>ARCHIVOS</h4>
                        <ul class="archive">
                            <li><a href="#">Marzo 2018<span class="num_posts">21</span></a></li>
                            <li><a href="#">Febrero 2018<span class="num_posts">24</span></a></li>
                            <li><a href="#">Enero 2018<span class="num_posts">38</span></a></li>
                           
                        </ul>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</main>

